Repository jenkins-x/jx-docs, pull requests merged in 2018-11, with the labels that each got.

#690 Use a correct URL to the workspace and add a note about signup.
  content/community.md
Labels: approved, size/XS

#643 add dev question zh
  content/faq/develop.zh.md
Labels: approved, needs-ok-to-test, size/M

#692 Merge further German JX talks for 2018, adding slides etc.
  content/demos/talks.md
Labels: approved, size/S

#721 Add Jenkins X talk at KubeCon
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#723 chore: add some Jenkins X meetups into the talks page
  content/demos/talks.md
Labels: approved, size/XS

#630 Add translation for install-on-cluster-what-happens
  content/getting-started/install-on-cluster-what-happens.zh.md
Labels: hacktoberfest, size/L

#732 Add talks: 2018-11-17 Korea Developer Conference at Seoul
  content/demos/talks.md
Labels: approved, needs-ok-to-test, size/XS

#754 Add wechat qrcode
  content/community.zh.md
  static/images/wechat.png
Labels: needs-ok-to-test, size/XS

#762 Add IBM Cloud as of 1.3.x
  content/contribute/roadmap.md
Labels: approved, lgtm, size/XS

#764 feat: add how to get jenkins username and password
  content/faq/issues.md
Labels: approved, size/XS
