Repository jenkins-x/jx-docs, pull requests merged in 2018-12, with the labels that each got.

#788 Update cloud-native-jenkins.md
  content/architecture/cloud-native-jenkins.md
Labels: approved, lgtm, size/XS

#783 fixes custom builder example so docker build succeeds
  content/getting-started/create-custom-builder.md
  content/getting-started/create-custom-builder.zh.md
Labels: approved, size/XS

#757 Update build-packs.md
  content/architecture/build-packs.md
Labels: approved, size/XS

#784 Fix formatting of code blocks in testing section of contributing docs
  content/contribute/development.md
Labels: approved, size/S

#789 feat: add `DEBUG=on` flag for debugging
  content/contribute/development.md
Labels: approved, size/XS

#805 fix(git): give a name when create git server
  content/developing/git.md
Labels: needs-ok-to-test, size/XS

#834 fix(Jenkinsfile): cleanup the old github credentials
  Jenkinsfile
Labels: approved, size/XS

#838 Add KubeCon video
  content/demos/talks.md
Labels: approved, ok-to-test, size/XS

#817 Fix link for 'jx get applications'
  content/developing/browsing.md
Labels: approved, ok-to-test, size/XS

#850 add docs on triaging issues on Jenkins X
  content/contribute/triage.md
Labels: approved, size/M

#851 tidy up triaging issues doc
  content/contribute/triage.md
Labels: approved, size/S

#852 add a screenshot to triage docs
  content/contribute/triage.md
  static/images/contribute/triage.png
Labels: approved, size/XS

#856 Update Google Analytics ID
  config.toml
Labels: needs-ok-to-test, size/XS
