Repository jenkins-x/jx-docs, pull requests merged in 2018-10, with the labels that each got.

#629 Typo fixed. Change defacto to default
  content/getting-started/install-on-cluster-what-happens.md
Labels: approved, hacktoberfest

#632 Add linuxsuren as an approver and reviewer
  OWNERS
Labels: approved, size/XS

#631 Fix the Chinese Jenkins website link
  config.toml
Labels: approved, hacktoberfest, size/XS

#634 Change the Jenkins Chinese website url
  config.toml
Labels: hacktoberfest, size/XS

#633 Patch for IKS create cluster doc
  content/commands/jx_create_cluster_iks.md
  content/getting-started/create-cluster.md
Labels: approved, lgtm, size/M

#637 Please merge a new Meetup talk, held in Frankfurt/Germany
  content/demos/talks.md
Labels: approved, needs-ok-to-test, size/S

#625 Merge hacking.md from jx repo into development page
  content/contribute/development.md
Labels: approved, lgtm, size/XL

#635 Fixed link
  content/demos/articles.md
Labels: approved, size/XS

#627 Removing non existent command jx step envrolebinding
  content/commands/jx_step_envrolebinding.md
Labels: approved

#639 add contribute zh translate
  content/contribute/_index.md
  content/contribute/_index.zh.md
Labels: hacktoberfest, size/S

#644 try and fix CI
  Jenkinsfile
Labels: approved, size/S

#640 add setup zh translate
  content/faq/setup.md
  content/faq/setup.zh.md
Labels: size/M

#642 Added cross-platform development section to contributing guidelines
  content/contribute/development.md
Labels: approved, size/S
