Repository jenkins-x/jx-docs, pull requests merged in 2019-07, with the labels that each got.

#1730 docs: Trivial update to documentation
  content/architecture/pod-templates.md
Labels: approved, lgtm, ok-to-test, size/XS

#1731 docs: office hours video/summary 2019-06-27
  content/community/2019-06-27.md
Labels: approved, size/S

#1733 docs: add CoC link
  content/community/_index.md
Labels: approved, size/XS

#1734 chore: add Commit messages
  content/contribute/development.md
Labels: approved, size/S

#1724 fix: Fixing a documentation error with getting password
  content/architecture/custom-jenkins.md
Labels: approved, ok-to-test, size/XS

#1732 fix: update /usr/local/bin
  content/getting-started/install.md
Labels: approved, ok-to-test, size/XS

#1750 fix: resolve issues in install documentation
  content/getting-started/install.md
Labels: approved, size/M

#1735 feat: adding proposed version stream diagram
  content/architecture/version-stream.md
  static/images/ProposedJXVersionStream.png
Labels: approved, size/XS

#1752 fix: Fix broken link
  content/architecture/components.md
Labels: approved, ok-to-test, size/XS

#1753 chore: add changelog.sh
  changelog.sh
  jenkins-x.yml
Labels: approved, size/XS

#1755 fix: made changelog.sh executable
  changelog.sh
Labels: approved, size/XS

#1756 chore: add more information regarding external-dns
  content/architecture/dns.md
Labels: approved, size/S

#1757 feat: Explain how e2e tests work for jx
  content/developing/continuous-integrating-jx-itself.md
  static/images/contribute/bdd-pipeline.png
  static/images/contribute/ci-jobs.png
Labels: approved, size/M

#1758 chore: update jx create cluster gke examples
  content/commands/jx_create_cluster_gke.md
Labels: approved, size/XS

#1759 chore: Update jx boot config links
  content/getting-started/boot.md
Labels: approved, lgtm, size/S

#1763 docs: update office hours
  content/community/_index.md
Labels: approved, lgtm, size/XS

#1764 chore: bump builder to avoid double tagging
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#1772 docs: add contributor summit post
  content/news/dw-jw-contributor-summit.md
  static/images/contributor_summit_sf.jpg
  static/images/old-Jenkins-x-Contributor-Summit.png
Labels: approved, size/M

#1775 docs: post dwjw lunch demos
  content/news/jenkinsworld-2019-demos.md
Labels: approved, size/M

#1762 docs: Added machine-learning docs
  content/developing/create-mlquickstart.md
Labels: approved, ok-to-test, size/L

#1778 docs: add pass code
  content/news/dw-jw-contributor-summit.md
Labels: approved, size/XS

#1769 fix: update eks.tf example
  content/getting-started/aws-terraform-install-gitops.md
Labels: approved, lgtm, ok-to-test, size/M

#1779 docs: Serverless deployments article
  content/news/serverless.md
Labels: approved, size/M

#1780 docs: Serverless deployments article
  content/news/serverless.md
Labels: approved, size/XS

#1777 fix #1761 linux install link broken
  content/getting-started/install.md
Labels: approved, needs-ok-to-test, size/XS

#1783 docs: update logos
  static/images/logo.png
  static/images/logo.svg
  themes/gohugoioTheme/layouts/partials/site-footer.html
  themes/gohugoioTheme/layouts/partials/svg/logo.svg
Labels: approved, size/L

#1784 docs: office hours 2019-07-25 plus update
  content/community/2019-07-25.md
  content/community/_index.md
Labels: approved, size/M

#1787 docs: update favicon
  static/apple-touch-icon.png
  static/favicon.ico
Labels: approved, size/XS

#1788 docs: update more logos to new logos
  static/images/logo-with-text.svg
  static/images/logo.png
Labels: approved, size/M

#1782 chore: added precommit configuration
  .pre-commit-config.yaml
Labels: approved, lgtm, size/XS

#1789 Jenkins x observability post
  content/news/jenkins-x-observability.md
  static/news/jenkins-x-observability/honeycomb_trace_example.png
Labels: size/L

#1790 Jenkins x observability post
  content/news/jenkins-x-observability.md
Labels: size/XS

#1776 chore: Add syntax reference for volumes
  content/architecture/pipeline-syntax-reference.md
Labels: size/XS

#1786 docs: Fixed typo
  content/architecture/jenkins-x-pipelines.md
Labels: approved, lgtm, ok-to-test, size/XS

#1781 docs: Fix broken links
  content/getting-started/multi-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#1792 docs: Blog post about new logo
  content/news/jenkins-x-new-logo.md
  static/news/new-logo-jenkins-x/jenkinsx-stacked-color.png
Labels: approved, lgtm, ok-to-test, size/M
