Repository jenkins-x/jx-docs, pull requests merged in 2019-03, with the labels that each got.

#1187 Remove the subtle wording around golang version
  content/contribute/development.md
Labels: size/XS

#1194 start a doc on how to get started with tekton and next gen pipelines
  content/getting-started/next-gen-pipeline.md
Labels: approved, size/M

#1201 Add Talk JAPANCONTAINERDAYS V18.12
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#1152 Add in QConLondon talk
  content/demos/talks.md
Labels: approved, needs-ok-to-test, size/XS

#1209 Delete no longer used file
  content/commands/jx_get_Apps.md
Labels: size/M

#1213 Viktor's talks
  content/demos/talks.md
Labels: approved, size/XS

#1207 Add JNation talk and CloudBees webinar
  content/demos/talks.md
Labels: size/XS

#1215 Add link to contribution page
  content/news/jenkins-x-joins-cdf.md
Labels: needs-ok-to-test, size/XS

#1217 Update jenkins-x-next-gen-pipeline-engine.md
  content/news/jenkins-x-next-gen-pipeline-engine.md
Labels: approved, size/XS

#1223 Fix the wrong images path under /zh
  themes/gohugoioTheme/layouts/partials/hero.html
Labels: approved, needs-ok-to-test, size/XS

#1233 Add Nicholas Duffy talk
  content/demos/talks.md
Labels: approved, needs-ok-to-test, size/XS

#1248 add latest office hours
  content/community.md
  content/demos/talks.md
Labels: size/XS

#1271 typofix：change 遗迹 to 以及
  content/about/concepts.zh.md
Labels: approved, needs-ok-to-test, size/XS

#1254 typofix:change kuberctl to kubectl
  content/getting-started/create-cluster.zh.md
Labels: approved, needs-ok-to-test, size/XS

#1232 Sharepointoscar tekton video embed
  content/commands/jx_create_cluster_aks.md
  content/commands/jx_create_cluster_aws.md
  content/commands/jx_create_cluster_eks.md
  content/commands/jx_create_cluster_gke.md
  content/commands/jx_create_cluster_gke_terraform.md
  content/commands/jx_create_cluster_iks.md
  content/commands/jx_create_cluster_minikube.md
  content/commands/jx_create_cluster_minishift.md
  content/commands/jx_create_cluster_oke.md
  content/faq/issues.md
  content/news/jenkins-x-next-gen-pipeline-engine.md
Labels: needs-ok-to-test, size/M

#1251 Add slides to Javaland / add talks to containerdays and Java Forum Stuttgart
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#1291 update about page
  content/about/_index.zh.md
Labels: approved, i18n, needs-ok-to-test, size/XS

#1288 Use correct argument; app no longer aliases application
  content/developing/browsing.md
  content/developing/browsing.zh.md
Labels: needs-ok-to-test, size/S
