Repository jenkins-x/jx-docs, pull requests merged in 2019-05, with the labels that each got.

#1453 latest office hours
  content/community/2019-05-3.md
Labels: size/S

#1455 progressive delivery article
  content/developing/progress-delivery.md
Labels: size/M

#1445 Update rbac docs
  content/architecture/access-control.md
  content/architecture/rbac.md
Labels: size/L

#1440 generate redirects
  config.toml
  content/about/_index.zh.md
  content/community.zh.md
  content/faq/_index.zh.md
  content/getting-started/create-cluster.zh.md
  content/getting-started/create-custom-builder.zh.md
  content/getting-started/install.zh.md
Labels: lgtm, size/S

#1452 change on premise to on premises
  content/getting-started/install-on-cluster.md
Labels: ok-to-test, size/XS

#1444 Use the correct chartmuseum url
  content/developing/preview.md
  content/faq/issues.md
Labels: size/XS

#1461 remove aliases from Chinese pages
  content/about/accelerate.zh.md
  content/about/concepts.zh.md
  content/about/features.zh.md
  content/about/license.zh.md
  content/architecture/_index.zh.md
  content/contribute/_index.zh.md
  content/contribute/apidocs.zh.md
  content/contribute/development.zh.md
  content/contribute/documentation.zh.md
  content/contribute/roadmap.zh.md
  content/contribute/triage.zh.md
  content/demos/_index.zh.md
  content/developing/_index.zh.md
  content/developing/promote.zh.md
  content/faq/develop.zh.md
  content/faq/faq.zh.md
  content/faq/issues.zh.md
  content/faq/jenkins.zh.md
  content/faq/setup.zh.md
  content/faq/technology.zh.md
  content/getting-started/_index.zh.md
  content/news/_index.zh.md
Labels: size/S

#1463 Progressive Delivery section
  content/developing/progress-delivery.md
  content/developing/progressive-delivery.md
  static/images/grafana-canary-analysis.png
Labels: size/L

#1467 Redirect progress-delivery -> progressive-delivery
  content/developing/progressive-delivery.md
Labels: size/XS

#1401 i18n: improve the faq.zh.md
  content/faq/faq.zh.md
Labels: approved, lgtm, ok-to-test, size/M

#1475 Fix styling so content doesn't overlap on larger screens
  themes/gohugoioTheme/layouts/_default/single.html
Labels: approved, lgtm, ok-to-test, size/XS

#1483 feat: add a preview chart
  .gitignore
  Dockerfile
  charts/preview/.helmignore
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/templates/_helpers.tpl
  charts/preview/templates/deployment.yaml
  charts/preview/templates/service.yaml
  charts/preview/values.yaml
  jenkins-x.yml
Labels: size/L

#1485 fix: set the URL correctly for previews
  jenkins-x.yml
Labels: size/XS

#1484 Apps commands
  content/apps/_index.md
Labels: approved, size/XS

#1490 The Evolution Of Jenkins Jobs And How We Got To The YAML-Based jenkin…
  content/demos/articles.md
Labels: approved, size/XS

#1498 Update jenkins-x-pipelines.md
  content/architecture/jenkins-x-pipelines.md
Labels: approved, ok-to-test, size/S

#1504 fixed typos
  content/getting-started/multi-cluster.md
Labels: approved, ok-to-test, size/XS

#1506 Typos in "Custom Jenkins" page
  content/architecture/custom-jenkins.md
Labels: approved, ok-to-test, size/S

#1508 fixed the term "registry" and cut out a superfluous word
  content/architecture/components.zh.md
Labels: approved, ok-to-test, size/XS

#1496 Fixed typo
  content/architecture/build-packs.md
Labels: needs-ok-to-test, size/XS

#1511 fixed the term "registry" to the term "repository" in the 4. ChartMuseum
  content/architecture/components.md
Labels: approved, ok-to-test, size/XS

#1515 update with new meeting link
  content/community/_index.md
Labels: approved, size/XS

#1517 Community Page and Tutorials
  content/community/_index.md
  content/getting-started/tutorials.md
  content/tutorials/_index.md
  content/tutorials/hosted/_index.md
  content/tutorials/video/_index.md
  content/tutorials/video/custom-builder.md
  content/tutorials/video/java-gradle-app.md
  themes/gohugoioTheme/layouts/tutorials/video/list.html
Labels: size/L

#1524 kubecon 2019 china talks
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#1534 chore: added status note for skaffold upgrade
  content/about/status.md
Labels: approved, size/S
