Repository jenkins-x/jx-docs, pull requests merged in 2019-12, with the labels that each got.

#2254 fix: Fix tags in the page Build, test and preview an app
  content/en/docs/getting-started/build-test-preview/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2264 docs: update jx upgrade commands
  content/en/docs/reference/commands/jx_upgrade.md
Labels: approved, size/XS

#2253 feat: Translate build-test-preview page into Spanish.
  content/es/docs/getting-started/build-test-preview/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#2267 fix: wrong url
  content/en/docs/reference/commands/jx_boot.md
Labels: approved, lgtm, ok-to-test, size/XS

#2268 docs: clean up ordering of steps to install
  content/en/docs/getting-started/setup/install/_index.md
Labels: approved, lgtm, size/S

#2274 fix: adding hferentschik to OWNERS
  OWNERS
Labels: approved, size/XS

#2273 chore: add more context around our use of pre-commit
  content/es/docs/contributing/code/_index.md
Labels: approved, size/XS

#2270 chore: adding sponsors section to the landing page
  assets/scss/_variables_project.scss
  content/en/_index.html
  layouts/partials/navbar.html
Labels: approved, size/M

#2272 fix: add aliases to capture old deep links that result in 404
  content/en/community/office_hours/2019-04-19.md
  content/en/docs/managing-jx/common-tasks/create-custom-builder.md
  content/en/docs/managing-jx/common-tasks/storage.md
  content/en/docs/managing-jx/tutorials/_index.md
  content/en/docs/reference/devpods.md
  content/en/docs/reference/multi-cluster.md
Labels: approved, size/S

#2276 fix: moving favicons to get the robot back instead of the default theme icon
  static/favicons/android-144x144.png
  static/favicons/android-192x192.png
  static/favicons/android-36x36.png
  static/favicons/android-48x48.png
  static/favicons/android-72x72.png
  static/favicons/android-96x196.png
  static/favicons/apple-touch-icon-120x120.png
  static/favicons/apple-touch-icon-152x152.png
  static/favicons/apple-touch-icon-167x167.png
  static/favicons/apple-touch-icon-180x180.png
  static/favicons/apple-touch-icon-60x60.png
  static/favicons/apple-touch-icon-76x76.png
  static/favicons/apple-touch-icon.png
  static/favicons/coast-228x228.png
  static/favicons/favicon-128x128.png
  static/favicons/favicon-16x16.png
  static/favicons/favicon-256x256.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon-48x48.png
  static/favicons/favicon-64x64.png
  static/favicons/favicon-96x96.png
  static/favicons/favicon.ico
  static/favicons/icon-128.png
  static/favicons/icon-512.png
  static/favicons/icon-60.png
  static/favicons/icon-90.png
  static/favicons/manifest.json
  static/favicons/mstile-144x144.png
  static/favicons/pwa-192x192.png
  static/favicons/pwa-512x512.png
  static/favicons/tile150x150.png
  static/favicons/tile310x150.png
  static/favicons/tile310x310.png
  static/favicons/tile70x70.png
Labels: approved, size/XS

#2278 chore: Adding CloudBees CI-CD powered by Jenkins X to the sponsor section.
  content/en/_index.html
  content/es/_index.html
  content/zh/_index.html
Labels: approved, lgtm, size/L

#2279 chore: updating the getting started landing page
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, size/S

#2280 docs: update office hours and events
  content/en/community/_index.md
  content/en/community/events/2019-12-dwjw.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/M

#2282 docs: fix numbering on install docs
  content/en/docs/getting-started/setup/install/_index.md
Labels: approved, size/S

#2283 docs: hide instructions for Cloud Shell
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/setup/install/_index.md
  content/en/docs/managing-jx/tutorials/google-hosted.md
Labels: approved, size/S

#2284 docs: Fix version command in install instructions
  content/en/docs/getting-started/setup/install/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2292 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2291 chore: adding references to cloudbees saas + UI
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/next.md
  content/en/docs/getting-started/setup/boot/_index.md
  content/en/docs/managing-jx/faq/_index.md
Labels: approved, size/M

#2299 feat: Existing Vault Instance note
  content/en/docs/reference/components/vault.md
Labels: size/XS

#2297 chore: adding LF footer + GA tracking
  assets/scss/_variables_project.scss
  layouts/partials/footer.html
  layouts/partials/scripts.html
Labels: approved, size/M

#2305 fix: typo then => than
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS
