Repository jenkins-x/jx-docs, pull requests merged in 2019-10, with the labels that each got.

#2049 fix: add bash completion FAQ
  content/en/docs/reference/components/vault.md
  content/en/docs/using-jx/faq/_index.md
Labels: size/S

#2050 fix: work around preview issue
  jenkins-x.yml
Labels: size/XS

#2048 docs: edits to community pages
  content/en/blog/news/hacktoberfest-2019.md
  content/en/community/_index.md
  content/en/community/events/_index.md
Labels: approved, size/M

#2045 chore: Add Carlos Sanchez talks
  content/en/docs/getting-started/demos-talks-posts/talks.md
Labels: approved, lgtm, size/S

#2054 fix: add json schema for jx-requirements.yml
  content/schemas/jx-requirements.json
Labels: size/L

#2053 fix: Typo. Misspelling of eksctl
  content/en/docs/getting-started/setup/create-cluster/amazon/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2051 docs: add outreachy blog post
  content/en/blog/news/outreachy-december-2019.md
  static/images/awesome-gophers-by-Ashley-McNamara/gopher_unicorn.png
  static/images/community/events/outreachy.png
Labels: size/M

#2030 fix: adding warning around git repos being created private by default
  content/en/docs/getting-started/setup/boot/_index.md
Labels: size/S

#2057 feat: updated diagram and added more information to version stream
  content/en/docs/concepts/version-stream.md
  static/images/jx-version-stream-v1.png
Labels: approved, lgtm, size/S

#2059 chore: Translate about index page to Chinese
  content/zh/about/_index.md
Labels: approved, ok-to-test, size/M

#2058 fix: add missing removal date in deprecation example
  content/en/about/maturity.md
Labels: approved, size/XS

#2068 fix: add docs on enabling backups
  content/en/docs/getting-started/setup/boot/_index.md
Labels: size/S

#2066 fix : Modified path create-cluster to /docs/getting-started/setup/create-cluster
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2071 docs: add page for anthos jx meetup
  content/en/community/events/22-10-2019-anthos-jx.md
  content/en/community/events/_index.md
  static/images/anthos-jx.jpg
Labels: approved, size/S

#2061 docs: remove $ from shell command
  content/en/docs/contributing/documentation/_index.md
Labels: size/XS

#2070 fix: Adds missing word
  content/en/docs/overview/accelerate.md
Labels: approved, lgtm, ok-to-test, size/XS

#2067 fix: Fixes broken link to Accelerate page
  content/en/about/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2064 chore: Add 'How do I inject Vault secrets...'
  content/en/docs/using-jx/faq/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#2072 fix: Modified path create-cluster to /zh/docs/getting-started/setup/create…
  content/zh/docs/getting-started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2074 docs: update 22-10-2019-anthos-jx.md
  content/en/community/events/22-10-2019-anthos-jx.md
Labels: approved, lgtm, ok-to-test, size/XS

#2075 fix: Update docs
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/setup/create-cluster/google.md
  content/en/docs/overview/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2076 docs: update oh
  content/en/community/_index.md
  content/en/community/events/_index.md
Labels: approved, size/XS

#2084 fix: Updated example to show long term storage enabled
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, size/XS

#2082 docs: add fosdem blog
  content/en/blog/news/fosdem-2020.md
  static/images/community/events/2020-fosdem.png
Labels: approved, size/M

#2085 fix: revert removed files
  content/en/docs/using-jx/faq/chatops.md
  static/apidocs/site/css/bootstrap.min.css
  static/apidocs/site/css/font-awesome.min.css
  static/apidocs/site/css/stylesheet.css
  static/apidocs/site/fonts/FontAwesome.otf
  static/apidocs/site/fonts/fontawesome-webfont.eot
  static/apidocs/site/fonts/fontawesome-webfont.svg
  static/apidocs/site/fonts/fontawesome-webfont.ttf
  static/apidocs/site/fonts/fontawesome-webfont.woff
  static/apidocs/site/fonts/fontawesome-webfont.woff2
  static/apidocs/site/index.html
  static/apidocs/site/jquery.scrollTo.min.js
  static/apidocs/site/js/bootstrap-3.3.7.min.js
  static/apidocs/site/js/jquery-3.2.1.min.js
  static/apidocs/site/navData.js
  static/apidocs/site/scroll.js
Labels: size/XXL

#2086 fix: Correct ingress enable tls key
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, size/XS

#2089 docs: organise community pages
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
  content/en/community/talksdemos.md
Labels: approved, size/L

#2090 docs: edits to community pages
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/newsletter.md
  content/en/community/office_hours/_index.md
  content/en/community/talksdemos/_index.md
Labels: approved, size/M

#2091 docs: Fix typo in external link
  content/en/about/_index.md
Labels: ok-to-test, size/XS

#2088 Viktor's talks
  content/en/docs/getting-started/demos-talks-posts/talks.md
Labels: approved, lgtm, size/S

#2101 fix: JW talk oscar andrew
  content/en/blog/news/jenkinsworld-lisbon-medina-bayer-talk.md
  static/images/jw-libson-oscar-andrew-talk.png
Labels: size/M

#2102 chore: Adding Oscar to the OWNERS file
  OWNERS
Labels: approved, size/XS

#2105 docs: fix DEBUG=on command
  content/en/docs/contributing/code/_index.md
Labels: approved, size/XS

#2106 docs: update office hours date
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2110 docs: add contributor summit lisbon
  content/en/blog/news/dwjw-lisbon-2019-contributor-summit.md
  static/images/community/events/jxcontribsummitlisbon.png
Labels: approved, size/M

#2111 docs: add talk
  content/en/community/talksdemos/_index.md
Labels: approved, size/XS

#2124 fix: Hacktoberfest - Added missing punctuation's in docs
  content/en/docs/concepts/_index.md
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/setup/_index.md
  content/en/docs/getting-started/setup/create-cluster/_index.md
  content/en/docs/getting-started/setup/create-cluster/amazon/_index.md
  content/en/docs/getting-started/setup/create-cluster/azure.md
  content/en/docs/getting-started/setup/create-cluster/google.md
  content/en/docs/getting-started/setup/install/_index.md
  content/en/docs/overview/changelog.md
  content/en/docs/overview/license.md
  content/en/docs/using-jx/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#2115 fix: appications -> applications
  content/en/docs/managing-jx/tutorials/serverless-apps.md
Labels: approved, lgtm, ok-to-test, size/XS

#2119 fix: deadlink fix.
  content/en/docs/contributing/documentation/apidocs.md
Labels: approved, lgtm, ok-to-test, size/XS

#2122 fix: link to promotion page
  content/en/docs/using-jx/faq/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2112 fix: Fix typo
  content/en/docs/getting-started/first-project/create-quickstart.md
Labels: approved, lgtm, ok-to-test, size/XS

#2114 fix: fixed link syntax
  content/en/docs/concepts/features.md
Labels: approved, lgtm, ok-to-test, size/XS

#2125 fix: Minor word choice change
  content/en/docs/concepts/jenkins-x-pipelines.md
Labels: approved, lgtm, ok-to-test, size/XS

#2128 fix: correct spelling of concatenate (Hacktoberfest)
  content/en/docs/contributing/code/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2121 fix: temporary fix for /about/features/ link
  content/en/docs/reference/components/custom-resources.md
Labels: approved, lgtm, ok-to-test, size/XS

#2139 docs: found new video links, removed unrecorded talks
  content/en/docs/getting-started/demos-talks-posts/talks.md
Labels: approved, lgtm, ok-to-test, size/L

#2127 fix: add alias for accelerate page on /about/accelerate
  content/en/docs/overview/accelerate.md
Labels: approved, size/XS

#2137 feat: Add link to newsletter archive
  content/en/community/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2136 fix: correct link error in issue #2129
  content/en/docs/concepts/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2130 feat: Add spanish structure.
  config.toml
  content/es/_index.html
  content/es/about/_index.md
  content/es/blog/_index.md
  content/es/blog/news/_index.md
  content/es/blog/news/jenkins-x-new-logo.md
  content/es/community/_index.md
  content/es/docs/_index.md
  content/es/docs/concepts/_index.md
  content/es/docs/contributing/_index.md
  content/es/docs/contributing/code/_index.md
  content/es/docs/contributing/documentation/_index.md
  content/es/docs/getting-started/_index.md
  content/es/docs/getting-started/demos-talks-posts/_index.md
  content/es/docs/getting-started/first-project/_index.md
  content/es/docs/getting-started/next.md
  content/es/docs/getting-started/setup/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/boot/background.md
  content/es/docs/getting-started/setup/boot/how-it-works.md
  content/es/docs/getting-started/setup/create-cluster/_index.md
  content/es/docs/getting-started/setup/create-cluster/amazon/_index.md
  content/es/docs/getting-started/setup/create-cluster/amazon/terraform.md
  content/es/docs/getting-started/setup/create-cluster/azure.md
  content/es/docs/getting-started/setup/create-cluster/google.md
  content/es/docs/getting-started/setup/install/_index.md
  content/es/docs/managing-jx/_index.md
  content/es/docs/managing-jx/common-tasks/_index.md
  content/es/docs/managing-jx/tutorials/_index.md
  content/es/docs/managing-jx/tutorials/google-hosted.md
  content/es/docs/overview/_index.md
  content/es/docs/reference/_index.md
  content/es/docs/using-jx/_index.md
  content/es/search.md
Labels: approved, lgtm, ok-to-test, size/XXL

#2142 chore: Merge new talks and slide updates
  content/en/community/talksdemos/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2151 chore: adding google site verification
  google21d4dcad00285f05.html
Labels: approved, size/XS

#2152 fix: place new verification file in the correct folder :facepalm:
  static/google21d4dcad00285f05.html
Labels: approved, size/XS

#2156 fix: add FAQ on disabling ingress controller
  content/en/docs/managing-jx/faq/boot.md
  content/en/docs/using-jx/faq/chatops.md
Labels: size/S
