Repository jenkins-x/jx-docs, pull requests merged in 2019-01, with the labels that each got.

#880 Spelling
  content/contribute/roadmap.md
Labels: approved, ok-to-test, size/XS

#888 Multi-language menu improve
  themes/gohugoioTheme/layouts/partials/languages-switcher.html
  themes/gohugoioTheme/layouts/partials/site-nav.html
Labels: approved, ok-to-test, size/S

#895 Spelling
  content/architecture/build-packs.md
Labels: needs-ok-to-test, size/XS

#902 update latest prow and knative build status
  content/about/status.md
Labels: approved, size/S

#905 Added prow docs
  content/architecture/cloud-native-jenkins.md
  content/architecture/prow.md
Labels: approved, size/L

#907 spelling and casing cleanup
  content/getting-started/install-on-cluster.md
Labels: approved

#893 …/blob/master/… considered harmful
  content/architecture/build-packs.md
Labels: approved, size/S

#906 Remove internal link
  content/architecture/prow.md
Labels: approved, size/XS

#910 misc spelling and casing fixes
  Localization_Chinese.md
  content/about/decisions.md
  content/architecture/components.md
  content/architecture/components.zh.md
  content/architecture/custom-resources.md
  content/architecture/prow.md
  content/commands/jx_controller_team.md
  content/commands/jx_create_cluster_aks.md
  content/commands/jx_create_cluster_aws.md
  content/commands/jx_create_cluster_eks.md
  content/commands/jx_create_cluster_gke.md
  content/commands/jx_create_cluster_gke_terraform.md
  content/commands/jx_create_cluster_iks.md
  content/commands/jx_create_cluster_minikube.md
  content/commands/jx_create_cluster_minishift.md
  content/commands/jx_create_cluster_oke.md
  content/commands/jx_create_codeship.md
  content/commands/jx_create_terraform.md
  content/commands/jx_install.md
  content/commands/jx_step_bdd.md
  content/contribute/documentation.zh.md
  content/developing/create-quickstart.md
  content/developing/create-quickstart.zh.md
  content/developing/git.zh.md
  content/developing/import.zh.md
  content/developing/issues.zh.md
  content/faq/issues.md
  content/getting-started/create-cluster.md
  content/getting-started/install-on-cluster-what-happens.md
  content/getting-started/install-on-cluster-what-happens.zh.md
  content/news/changes-26-november-2018.md
  content/news/changes-27-april-2018.md
  themes/gohugoioTheme/layouts/partials/home-page-sections/open-source-involvement.html
  themes/gohugoioTheme/layouts/partials/svg/github-corner.svg
Labels: needs-ok-to-test, size/L

#914 update office hours meeting URL
  content/community.md
Labels: approved, size/XS

#915 cleanup office hours section
  content/community.md
Labels: approved, size/XS

#917 Add space between text and link
  content/community.md
Labels: approved, ok-to-test, size/XS

#933 Move JX Talk in Würzburg to January
  content/demos/talks.md
Labels: approved, ok-to-test, size/XS

#945 chore(docs) document the security process
  config.toml
  content/security.md
Labels: size/M

#941 Word 'alot' should be replaced with 'a lot'
  content/news/jenkins-x-first-birthday.md
Labels: approved, needs-ok-to-test, size/XS

#956 Add some notes on how PR merging works
  content/contribute/development.md
Labels: size/S

#962 Fix typos in Git docs
  content/developing/git.md
Labels: size/XS

#951 Fix typo
  content/getting-started/create-custom-builder.md
Labels: needs-ok-to-test, size/XS

#971 Added new entry to FAQ on how to update jx binary when using serverless jenkins
  content/faq/setup.md
Labels: size/M

#975 (docs) Correct the create token command
  content/faq/issues.md
Labels: size/XS

#976 updates to add sponsor page and replacing use of roadmap with 'futures' …
  config.toml
  content/about/_index.md
  content/about/decisions.md
  content/about/features.md
  content/contribute/_index.md
  content/contribute/roadmap.md
  content/contribute/roadmap.zh.md
  content/news/changes-11-april-2018.md
  content/news/changes-27-april-2018.md
  content/sponsors.md
  static/images/sponsors/cb.svg
Labels: approved, size/M

#988 Fix typo in Getting Started > Configuration
  content/getting-started/config.md
Labels: approved, ok-to-test, size/XS

#990 Viktor Farcic - talks
  content/demos/talks.md
Labels: approved, ok-to-test, size/XS

#998 Add brainstorming doc to Plans page
  content/contribute/roadmap.md
Labels: approved, size/XS

#1007 chore: add deanesmith as approver for docs
  OWNERS
Labels: approved, size/XS

#991 Viktor Farcic - future talks and workshops
  content/demos/talks.md
Labels: approved, ok-to-test, size/XS

#1008 chore: Add vfarcic to approvers
  OWNERS
Labels: approved, size/XS

#1006 feat: start to document apps framework
  config.toml
  content/apps/_index.md
  content/apps/worked-example.md
  content/extending/_index.md
Labels: approved, size/L

#1010 Godoc
  content/apps/_index.md
  content/apps/worked-example.md
Labels: approved, size/S
