Repository jenkins-x/jx-docs, pull requests merged in 2019-02, with the labels that each got.

#1027 docs: fix path to buildpacks in quickstart
  README.md
  content/developing/create-quickstart.md
Labels: size/S

#1018 Added SourceRepository CRD info
  content/architecture/custom-resources.md
Labels: size/XS

#1026 Updated img source in concepts
  content/about/concepts.md
Labels: needs-ok-to-test, size/XS

#974 Update GKE "Connecting to the cluster from your laptop" section
  content/getting-started/create-cluster.md
Labels: needs-ok-to-test, size/XS

#1012 What is Jenkins X
  content/about/what.md
Labels: size/M

#1044 feat: document how to write apidocs
  content/contribute/apidocs.md
Labels: size/L

#1045 feat: explain how code generation works
  content/contribute/development.md
Labels: approved, size/S

#1017 Use GitHub permalinks
  content/architecture/storage.md
Labels: approved, size/XS

#1046 feat: added status update for the nexus update
  content/about/status.md
Labels: approved, size/S

#1054 Adding video at JDD Poland
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#1066 Changing value stream to version stream
  content/architecture/version-stream.md
Labels: approved, size/XS

#1067 Update version-stream.md
  content/architecture/version-stream.md
Labels: approved, size/XS

#1070 improved sentence
  content/architecture/version-stream.md
Labels: approved, size/XS

#1071 feat: added note about regression in upgrade process
  content/about/status.md
Labels: approved, size/S

#1076 update office hours zoom URL
  content/community.md
Labels: approved, size/XS

#1131 add news on next gen pipeline initiative
  content/news/jenkins-x-next-gen-pipeline-engine.md
Labels: approved, size/S

#1132 rename build pipeline to tekton pipeline as it has been announced
  content/news/jenkins-x-next-gen-pipeline-engine.md
Labels: approved, size/XS

#1135 Google AppDev slides
  content/demos/talks.md
Labels: approved, size/XS

#1122 Added new talks (and slides etc.) by @ascheman and @nbyl
  content/demos/talks.md
Labels: approved, needs-ok-to-test, size/S

#1114 close #1113 correct link for "created a Kubernetes cluster with Jenki…
  content/getting-started/next.md
Labels: needs-ok-to-test, size/XS

#1145 jx-docs enhancement: Developing / Getting Started
  content/developing/_index.md
  static/images/developing/developer_workflow_ide.png
  static/images/developing/developer_workflow_theia.png
Labels: needs-ok-to-test, size/L

#1138 Add talk at gr8conf + Re-order by date
  content/demos/talks.md
Labels: needs-ok-to-test, size/XS

#1137 fix image links
  content/about/concepts.md
Labels: needs-ok-to-test, size/XS
