Repository jenkins-x/jx-docs, pull requests merged in 2019-04, with the labels that each got.

#1289 modify text on home page for zh
  themes/gohugoioTheme/i18n/zh.toml
Labels: approved, i18n, needs-ok-to-test, size/XS

#1290 docs: development guide i18n for zh_CN
  content/contribute/development.zh.md
Labels: approved, i18n, needs-ok-to-test, size/L

#1313 Viktor's talks
  content/demos/talks.md
Labels: approved, size/XS

#1303 update next.zh.md to keep pace with next.md
  content/getting-started/next.zh.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1317 feat: added tekton pipeline
  Jenkinsfile
  jenkins-x.yml
Labels: approved, size/L

#1318 fix: pushing to upstream
  jenkins-x.yml
Labels: approved, size/XS

#1319 debug: added sleep command for debug
  jenkins-x.yml
Labels: approved, size/XS

#1320 debug: attempting to test the workingDir
  jenkins-x.yml
Labels: approved, size/XS

#1321 feat: refactored website update into script
  update-website.sh
Labels: approved, size/S

#1322 feat: refactored into script
  jenkins-x.yml
Labels: approved, size/M

#1323 fixed: update website script
  update-website.sh
Labels: approved, size/XS

#1324 docs: documentation i18n add the missing anchor
  content/contribute/documentation.zh.md
Labels: needs-ok-to-test, size/XS

#1325 fix: added in missing env vars to generate 'production' site
  jenkins-x.yml
Labels: approved, size/XS

#1304 update install.zh.md to keep pace with install.md
  content/getting-started/install.zh.md
Labels: approved, lgtm, ok-to-test, size/M

#1305 update config.zh.md to keep pace with config.md
  content/getting-started/config.zh.md
Labels: approved, lgtm, ok-to-test, size/M

#1330 Webhooks in local clusters
  content/getting-started/create-cluster.md
Labels: approved, size/XS

#1333 Sharepointoscar managing jenkins x infra
  content/architecture/components.md
  content/faq/develop.md
  content/news/Provision-Jenkins-x-k8s-clusters-terraform.md
  static/images/jenkinsTerraform.png
Labels: needs-ok-to-test, size/L

#1344 add latest office hours
  content/community.md
Labels: size/XS

#1329 fix: updating docs around code generation
  content/contribute/apidocs.md
  content/contribute/development.md
Labels: approved, size/M

#1350 Fix another instance of improper alias
  content/developing/devpods.md
Labels: needs-ok-to-test, size/XS

#1337 i18n: translate sponsors.md to chinese
  content/sponsors.zh.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1336 i18n: translate source.md to chinese
  content/architecture/source.zh.md
Labels: lgtm, needs-ok-to-test, size/M

#1334 i18n: translate manage-via-gitops.md to chinese
  content/getting-started/manage-via-gitops.zh.md
Labels: approved, needs-ok-to-test, size/M

#1351 add menus for zh-CN
  config.toml
Labels: approved, lgtm, needs-ok-to-test, size/S

#1357 added richer diagram for static jenkins deployment
  content/architecture/diagram.md
  static/images/ArchitectureStaticJenkins.png
Labels: needs-ok-to-test, size/S

#1364 Fix typos and general verbiage
  content/architecture/diagram.md
Labels: needs-ok-to-test, size/XS

#1306 update roadmap.zh.md
  content/contribute/roadmap.zh.md
Labels: approved, needs-ok-to-test, size/M

#1352 i18n:translate triage.md to chinese
  content/contribute/triage.zh.md
Labels: approved, needs-ok-to-test, size/M

#1360 fix 404 of /zh/extending/
  config.toml
Labels: needs-ok-to-test, size/XS

#1368 docs tidy up
  content/developing/serverless-apps.md
Labels: size/M

#1377 Sharepointoscar office hours layout
  themes/gohugoioTheme/layouts/partials/hero.html
Labels: needs-ok-to-test, size/XS

#1378 Sharepointoscar office hours layout
  themes/gohugoioTheme/layouts/partials/hero.html
Labels: needs-ok-to-test, size/S

#1379 Serverless
  content/architecture/diagram.md
  static/images/ArchitectureServerlessJenkins.png
Labels: approved, size/XS

#1332 Create EKS cluster and vault requirements on AWS with terraform
  content/getting-started/aws-terraform-install-gitops.md
  content/getting-started/install-on-cluster.md
Labels: needs-ok-to-test, size/L

#1388 added JenkinsWorld Awards
  content/news/jenkinsworld.md
  static/images/dwjw-2019-io.jpg
Labels: needs-ok-to-test, size/M

#1389 Sharepointoscar newsitem author field
  content/news/jenkinsworld.md
  content/news/provision-jx-clusters-terraform.md
  themes/gohugoioTheme/layouts/news/single.html
Labels: needs-ok-to-test, size/XS

#1390 Sharepointoscar newsitem author field
  themes/gohugoioTheme/layouts/news/single.html
  themes/gohugoioTheme/layouts/partials/boxes-section-summaries.html
Labels: needs-ok-to-test, size/XS

#1391 Sharepointoscar newsitem author field
  themes/gohugoioTheme/layouts/news/single.html
Labels: needs-ok-to-test, size/XS

#1396 latest office hours
  content/community/april-18.md
Labels: approved, size/S

#1382 Update license per issue #3398
  LICENSE.md
Labels: approved, size/L

#1331 i18n zh_CN apidocs page
  content/contribute/apidocs.zh.md
Labels: needs-ok-to-test, size/L

#1412 Highlight ChartMuseum config with header
  content/getting-started/config.md
Labels: needs-ok-to-test, size/XS

#1403 Update april-18.md
  content/community/april-18.md
Labels: needs-ok-to-test, size/XS

#1413 Added Viktor's articles
  content/demos/articles.md
Labels: approved, size/XS

#1421 provision with terraform
  content/news/provision-jx-clusters-terraform.md
Labels: needs-ok-to-test, size/XS

#1424 Sposcar install gke cluster with bot
  content/getting-started/install-gke-with-bot-tutorial.md
Labels: needs-ok-to-test, size/S

#1425 Sposcar install gke cluster with bot
  content/getting-started/install-gke-with-bot-tutorial.md
Labels: needs-ok-to-test, size/S

#1434 March 2019 talks
  content/demos/talks.md
Labels: approved, size/XS
