Repository jenkins-x/jx-docs, pull requests merged in 2019-11, with the labels that each got.

#2165 fix: add a couple more pipeline FAQs
  content/en/docs/using-jx/faq/pipelines.md
Labels: size/M

#2161 feat: translated to Spanish Getting started section
  content/es/docs/getting-started/build-test-preview/_index.md
  content/es/docs/getting-started/demos-talks-posts/_index.md
  content/es/docs/getting-started/demos-talks-posts/create_cluster.md
  content/es/docs/getting-started/demos-talks-posts/create_cluster_gke.md
  content/es/docs/getting-started/demos-talks-posts/create_spring.md
  content/es/docs/getting-started/demos-talks-posts/devoxx-uk-2018.md
  content/es/docs/getting-started/demos-talks-posts/kubecon-2018.md
  content/es/docs/getting-started/first-project/_index.md
  content/es/docs/getting-started/first-project/create-quickstart.md
  content/es/docs/getting-started/promotion/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/boot/background.md
  content/es/docs/getting-started/setup/boot/how-it-works.md
  content/es/docs/getting-started/setup/create-cluster/amazon/_index.md
  content/es/docs/getting-started/setup/create-cluster/amazon/terraform.md
  content/es/docs/getting-started/setup/create-cluster/azure.md
  content/es/docs/getting-started/setup/create-cluster/google.md
Labels: approved, ok-to-test, size/XL

#2164 fix: update broken link and add GCP references for clarity
  content/en/docs/contributing/code/contribute_dns.md
Labels: approved, lgtm, size/S

#2160 fix: correct helm cli.
  content/en/docs/getting-started/promotion/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2167 fix: corrected layout of community sub-pages
  content/en/community/events/2019-12-dwjw.md
  content/en/community/events/22-10-2019-anthos-jx.md
  content/en/community/events/_index.md
  content/en/community/newsletter/_index.md
  content/en/community/office_hours/2019-02-21.md
  content/en/community/office_hours/2019-03-21.md
  content/en/community/office_hours/2019-04-04.md
  content/en/community/office_hours/2019-04-19.md
  content/en/community/office_hours/2019-05-03.md
  content/en/community/office_hours/2019-05-30.md
  content/en/community/office_hours/2019-06-27.md
  content/en/community/office_hours/2019-07-25.md
  content/en/community/office_hours/_index.md
  content/en/community/office_hours/archives.md
  content/en/community/talksdemos/_index.md
Labels: approved, size/S

#2148 docs: add rich event metadata
  content/en/blog/news/fosdem-2020.md
  content/en/community/events/2019-12-dwjw.md
  content/en/community/events/_index.md
Labels: approved, ok-to-test, size/M

#2166 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/22-10-2019-anthos-jx.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/S

#2169 chore: improve example for git token 401
  content/en/docs/managing-jx/faq/issues.md
Labels: approved, lgtm, ok-to-test, size/XS

#2171 docs: add rich events readme
  content/en/community/events/README.md
Labels: approved, lgtm, ok-to-test

#2174 feat: Concepts section translated into Spanish
  content/es/docs/concepts/_index.md
  content/es/docs/concepts/components.md
  content/es/docs/concepts/diagram.md
  content/es/docs/concepts/features.md
  content/es/docs/concepts/jenkins-x-pipelines.md
  content/es/docs/concepts/technology.md
  content/es/docs/concepts/version-stream.md
  content/es/docs/getting-started/demos-talks-posts/create_spring.md
  content/es/docs/getting-started/first-project/create-quickstart.md
  content/es/docs/getting-started/promotion/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/boot/background.md
  content/es/docs/getting-started/setup/boot/how-it-works.md
Labels: approved, lgtm, ok-to-test, size/XL

#2172 docs: Fix link to parameters.tmpl.schema.json
  content/en/docs/getting-started/setup/boot/how-it-works.md
Labels: approved, lgtm, ok-to-test, size/XS

#2175 feat: About section translated into Spanish
  content/es/about/_index.md
  content/es/about/maturity.md
Labels: approved, lgtm, ok-to-test, size/L

#2180 fix: added docs on boot and repository
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, size/M

#2181 feat: Update repository section based on the english file.
  content/es/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#2168 fix: correct ingress example indenting
  content/en/docs/reference/components/vault.md
Labels: approved, lgtm, ok-to-test, size/M

#2189 chore: Translate example page into Spanish.
  content/es/docs/managing-jx/examples/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2188 fix: page not found link.
  content/en/docs/managing-jx/common-tasks/create-custom-builder.md
Labels: approved, lgtm, ok-to-test, size/XS

#2187 feat: Common tasks section translated into Spanish
  content/es/docs/concepts/components.md
  content/es/docs/concepts/features.md
  content/es/docs/concepts/jenkins-x-pipelines.md
  content/es/docs/concepts/technology.md
  content/es/docs/concepts/version-stream.md
  content/es/docs/getting-started/_index.md
  content/es/docs/getting-started/setup/create-cluster/_index.md
  content/es/docs/getting-started/setup/create-cluster/amazon/terraform.md
  content/es/docs/managing-jx/common-tasks/_index.md
  content/es/docs/managing-jx/common-tasks/access-control.md
  content/es/docs/managing-jx/common-tasks/create-custom-builder.md
  content/es/docs/managing-jx/common-tasks/dns.md
  content/es/docs/managing-jx/common-tasks/security-features.md
  content/es/docs/managing-jx/common-tasks/storage.md
  content/es/docs/managing-jx/common-tasks/tls.md
  content/es/docs/managing-jx/common-tasks/upgrade-jx.md
Labels: approved, lgtm, ok-to-test, size/XL

#2191 feat: Faq page translated into Spanish
  content/es/docs/overview/faq.md
Labels: approved, lgtm, ok-to-test, size/M

#2183 docs: fix link to deprecated docs, make copy edits
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#2193 fix: Fix opinionated translation.
  content/es/docs/overview/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2196 fix: avoid using bad urls
  content/en/docs/managing-jx/faq/issues.md
Labels: size/XS

#2201 docs: add hackathon post
  content/en/blog/news/2019-hackathon-lisbon.md
  content/en/community/events/_index.md
  static/images/community/events/throwing-x-kubecon-china-2019.jpg
Labels: approved, size/M

#2202 docs: fix typo
  content/en/community/events/_index.md
Labels: approved, size/XS

#2208 feat: Faq pages form managing-jx section translated into Spanish
  content/es/docs/managing-jx/faq/_index.md
  content/es/docs/managing-jx/faq/boot.md
  content/es/docs/managing-jx/faq/issues.md
Labels: approved, lgtm, ok-to-test, size/XL

#2209 docs: fix link
  content/en/docs/reference/commands/jx_boot.md
Labels: approved, size/XS

#2212 fix: removing aliases from spanish pages to avoid them clashing with the ones for english
  content/es/blog/news/jenkins-x-new-logo.md
  content/es/docs/_index.md
  content/es/docs/concepts/_index.md
  content/es/docs/concepts/jenkins-x-pipelines.md
  content/es/docs/contributing/_index.md
  content/es/docs/getting-started/_index.md
  content/es/docs/getting-started/demos-talks-posts/_index.md
  content/es/docs/getting-started/demos-talks-posts/create_cluster_gke.md
  content/es/docs/getting-started/demos-talks-posts/create_spring.md
  content/es/docs/getting-started/promotion/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/create-cluster/_index.md
  content/es/docs/getting-started/setup/install/_index.md
  content/es/docs/managing-jx/common-tasks/access-control.md
  content/es/docs/managing-jx/faq/_index.md
  content/es/docs/managing-jx/faq/boot.md
  content/es/docs/managing-jx/faq/issues.md
Labels: approved, size/M

#2204 fix: Fixed minor typo on accelerate.md
  content/en/docs/overview/accelerate.md
Labels: approved, lgtm, ok-to-test, size/XS

#2207 feat: Faq section translated into Spanish
  content/es/docs/using-jx/faq/_index.md
  content/es/docs/using-jx/faq/chatops.md
  content/es/docs/using-jx/faq/pipelines.md
Labels: approved, lgtm, ok-to-test, size/XL

#2213 feat: Components section translated into Spanish
  content/es/docs/reference/components/_index.md
  content/es/docs/reference/components/build-packs.md
  content/es/docs/reference/components/cloud-native-jenkins.md
  content/es/docs/reference/components/custom-jenkins.md
  content/es/docs/reference/components/custom-resources.md
  content/es/docs/reference/components/decisions.md
  content/es/docs/reference/components/docker-registry.md
  content/es/docs/reference/components/git.md
  content/es/docs/reference/components/helm3.md
  content/es/docs/reference/components/lighthouse.md
  content/es/docs/reference/components/pod-templates.md
  content/es/docs/reference/components/prow.md
  content/es/docs/reference/components/source.md
  content/es/docs/reference/components/vault.md
Labels: approved, lgtm, ok-to-test, size/XXL

#2200 feat: Adding repositories section translated into Spanish
  content/es/docs/using-jx/creating/_index.md
  content/es/docs/using-jx/creating/create-camel.md
  content/es/docs/using-jx/creating/create-mlquickstart.md
  content/es/docs/using-jx/creating/create-spring.md
  content/es/docs/using-jx/creating/import.md
Labels: approved, lgtm, ok-to-test, size/L

#2199 chore: add htmltest to pipeline
  .htmltest.yml
  config.toml
  content/es/docs/managing-jx/faq/_index.md
  content/es/docs/managing-jx/faq/boot.md
  content/es/docs/managing-jx/faq/issues.md
  content/es/docs/reference/components/build-packs.md
  content/es/docs/reference/components/cloud-native-jenkins.md
  content/es/docs/reference/components/custom-resources.md
  content/es/docs/reference/components/decisions.md
  content/es/docs/reference/components/git.md
  content/es/docs/reference/components/lighthouse.md
  content/es/docs/reference/components/pod-templates.md
  content/es/docs/reference/components/source.md
  content/es/docs/reference/components/vault.md
  content/es/docs/using-jx/creating/create-camel.md
  content/es/docs/using-jx/creating/create-mlquickstart.md
  content/es/docs/using-jx/creating/create-spring.md
  content/es/docs/using-jx/creating/import.md
  content/es/docs/using-jx/faq/_index.md
  content/es/docs/using-jx/faq/chatops.md
  content/es/docs/using-jx/faq/pipelines.md
  content/zh/docs/using-jx/common-tasks/create-spring.md
  jenkins-x.yml
Labels: approved, size/L

#2216 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2217 docs: add artwork page, link
  content/en/docs/artwork/_index.md
Labels: approved, size/S

#2227 fix: Minor fixes to docs contribution and pipeline
  content/en/docs/contributing/documentation/_index.md
  jenkins-x.yml
Labels: approved, size/XS

#2231 docs: fix rendering of artwork page
  content/en/docs/artwork/_index.md
Labels: approved, size/XS

#2232 fix: comment out htmltest in production pipeline for now
  jenkins-x.yml
Labels: approved, size/S

#2233 fix: adding/moving static files needed for prod website
  static/CNAME
  static/LICENSE
  static/android-144x144.png
  static/android-192x192.png
  static/android-36x36.png
  static/android-48x48.png
  static/android-72x72.png
  static/android-96x196.png
  static/apple-touch-icon-120x120.png
  static/apple-touch-icon-152x152.png
  static/apple-touch-icon-167x167.png
  static/apple-touch-icon-180x180.png
  static/apple-touch-icon-60x60.png
  static/apple-touch-icon-76x76.png
  static/browserconfig.xml
  static/coast-228x228.png
  static/favicon-128x128.png
  static/favicon-16x16.png
  static/favicon-256x256.png
  static/favicon-32x32.png
  static/favicon-48x48.png
  static/favicon-64x64.png
  static/favicon-96x96.png
  static/favicon.ico
  static/favicons/favicon.ico
  static/icon-128.png
  static/icon-512.png
  static/icon-60.png
  static/icon-90.png
  static/manifest.json
  static/mstile-144x144.png
  static/pwa-192x192.png
  static/pwa-512x512.png
  static/tile150x150.png
  static/tile310x150.png
  static/tile310x310.png
  static/tile70x70.png
Labels: approved, size/M

#2235 fix: remove old site before generating and pushing the new site
  jenkins-x.yml
  static/.nojekyll
Labels: approved, size/S

#2237 fix: remove out-dated tutorial for installing jx on gke
  content/en/docs/managing-jx/tutorials/install-gke-with-bot-tutorial.md
Labels: approved, size/XL

#2240 fix: Typo in word other
  content/en/docs/using-jx/faq/_index.md
Labels: approved, needs-ok-to-test, size/XS

#2248 fix: add redirect
  README.md
  content/en/docs/reference/pipeline-syntax-reference.md
Labels: approved, size/S

#2250 fix: Add redirect from old TLS URL to boot docs
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, size/XS

#2238 feat: Build, test and preview an app
  content/en/docs/getting-started/build-test-preview/_index.md
Labels: approved, lgtm, ok-to-test, size/L

#2252 fix: add docss on how to create a quickstart
  content/en/docs/using-jx/creating/create-quickstart.md
Labels: size/S

#2257 docs: add outreachy welcome post
  content/en/blog/news/2019-outreachy-welcome.md
  static/images/community/events/outreachy_group_photo.png
Labels: approved, size/S
