Repository jenkins-x/jx-docs, pull requests merged in 2019-06, with the labels that each got.

#1574 Docker jfrog registry
  content/architecture/docker-registry.md
Labels: size/S

#1577 Docker jfrog registry
  content/architecture/docker-registry.md
Labels: size/S

#1594 Ingress article
  content/demos/articles.md
Labels: approved, size/XS

#1596 Update Contribution section of README.md
  README.md
Labels: approved, ok-to-test, size/XS

#1598 Add JenkinsWorld agenda
  content/news/jenkinsworld-2019-agenda.md
  static/images/2019-dwjw-san-fran-rev.png
Labels: approved, ok-to-test, size/M

#1608 Update: Jenkins X no longer sub-project
  content/about/_index.md
Labels: approved, size/XS

#1609 add Kara as an approver
  OWNERS
Labels: approved, size/XS

#1626 Grammatical changes
  content/architecture/prow.md
Labels: approved, ok-to-test, size/XS

#1625 Grammatical errors
  content/architecture/prow.md
Labels: approved, ok-to-test, size/XS

#1627 Typos
  content/news/serverless-jenkins.md
Labels: approved, ok-to-test, size/XS

#1588 Fixed typo.
  content/commands/jx_edit_branchpattern.md
Labels: approved, ok-to-test, size/XS

#1554 Fix broken link for "jx_add_app"
  content/getting-started/manage-via-gitops.md
Labels: approved, lgtm, ok-to-test, size/XS

#1557 Fix a couple broken links
  content/developing/devpods.md
Labels: approved, lgtm, ok-to-test, size/XS

#1580 Update minor typo
  content/getting-started/multi-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#1558 Update jenkins-x-pipelines.md
  content/architecture/jenkins-x-pipelines.md
Labels: approved, lgtm, ok-to-test, size/XS

#1585 Fix documentation link
  content/commands/jx_controller_team.md
  content/commands/jx_create_cluster_aks.md
  content/commands/jx_create_cluster_aws.md
  content/commands/jx_create_cluster_eks.md
  content/commands/jx_create_cluster_gke.md
  content/commands/jx_create_cluster_gke_terraform.md
  content/commands/jx_create_cluster_iks.md
  content/commands/jx_create_cluster_minikube.md
  content/commands/jx_create_cluster_minishift.md
  content/commands/jx_create_cluster_oke.md
  content/commands/jx_create_codeship.md
  content/commands/jx_create_terraform.md
  content/commands/jx_install.md
  content/commands/jx_step_bdd.md
  content/getting-started/install-on-cluster.md
Labels: approved, lgtm, ok-to-test, size/M

#1643 Update serverless-apps.md
  content/developing/serverless-apps.md
Labels: approved, lgtm, ok-to-test, size/XS

#1646 Update office hours
  content/community/_index.md
Labels: approved, size/XS

#1648 Add 2019-05-30 office hours recap and video
  content/community/2019-05-30.md
  content/community/_index.md
Labels: approved, size/S

#1647 Update kube-context.md
  content/developing/kube-context.md
Labels: approved, lgtm, ok-to-test, size/XS

#1657 Update office hours
  content/community/_index.md
Labels: approved, size/XS

#1658 Update calendar display
  content/community/_index.md
Labels: approved, size/XS

#1662 Edit office hours info
  content/community/_index.md
Labels: approved, size/XS

#1669 Blog post with instructions to install in Alibaba cloud
  content/news/install-jx-alibaba.md
  static/images/alibaba-cloud-logo.png
Labels: size/L

#1671 chore: use alibaba svg logo
  content/news/install-jx-alibaba.md
  static/images/alibaba-cloud-logo.png
  static/images/alibaba-cloud-logo.svg
Labels: size/XS

#1681 fix: prometheus addon is not needed for flagger
  content/developing/progressive-delivery.md
Labels: size/XS

#1676 Google storage is not blocked in China
  content/news/install-jx-alibaba.md
Labels: size/XS

#1654 fixed last `kubectl create secret ...` command
  content/architecture/docker-registry.md
Labels: needs-ok-to-test, size/XS

#1645 Update config.md
  content/getting-started/config.md
Labels: lgtm, ok-to-test, size/XS

#1583 Fix AWS IAM Policy for Vault user to get access to KMS key
  content/getting-started/aws-terraform-install-gitops.md
Labels: needs-ok-to-test, size/XS

#1493 Feat: add plugins doc
  content/apps/_index.md
  content/apps/plugins.md
Labels: size/M

#1535 Mass migration of content from Cloudbees Jenkins X content back to community docs
  content/getting-started/create-cluster.md
  content/getting-started/install.md
  content/getting-started/upgrade-jx.md
  themes/gohugoioTheme/layouts/_default/baseof.html
Labels: ok-to-test, size/L

#1682 Add JX Pipeline syntax reference doc
  content/architecture/pipeline-syntax-reference.md
Labels: size/L

#1686 Use the correct anchor for differences between JX and Jenkins pipelines
  content/faq/pipelines.md
Labels: needs-ok-to-test, size/XS

#1688 Adding an example of defining a full pipeline in jenkins-x.yml
  content/architecture/pipeline-syntax-reference.md
Labels: size/L

#1693 adding docs for cert-manager issue
  content/faq/issues.md
Labels: needs-ok-to-test, size/M

#1701 fix: instructions to create the alibaba namespace
  content/news/install-jx-alibaba.md
Labels: approved, lgtm, size/S

#1702 An attempt to make the improve button more visible
  themes/gohugoioTheme/layouts/_default/page.html
  themes/gohugoioTheme/layouts/_default/single.html
  themes/gohugoioTheme/layouts/news/single.html
  themes/gohugoioTheme/layouts/partials/page-edit.html
  themes/gohugoioTheme/static/dist/main.css
Labels: size/XS

#1708 Adding information on external-dns
  content/architecture/dns.md
Labels: size/M

#1716 Add article: Jenkins X - TLS enabled Previews
  content/demos/articles.md
Labels: needs-ok-to-test, size/XS

#1720 docs: update office hours date
  content/community/_index.md
Labels: approved, size/XS

#1723 docs: change for k8s to on k8s
  content/about/_index.md
  content/documentation.md
Labels: approved, size/XS

#1725 docs: June articles by Viktor
  content/demos/articles.md
Labels: approved, size/XS

#1726 docs: June talks and workshops by Viktor
  content/demos/talks.md
Labels: approved, size/S
