Repository jenkins-x/jx-docs, pull requests merged in 2019-08, with the labels that each got.

#1796 chore: document the checks we do on PRs
  content/contribute/development.md
Labels: approved, lgtm, size/S

#1795 chore: describe how to handle DCO
  content/contribute/development.md
Labels: approved, lgtm, size/M

#1801 fix: remove footer img text
  themes/gohugoioTheme/layouts/partials/site-footer.html
Labels: approved, lgtm, size/XS

#1803 fix: typo in Pre and Post Validation
  content/getting-started/boot.md
Labels: approved, lgtm, size/XS

#1804 chore: add PR review guide
  content/contribute/pullrequestreview.md
Labels: size/L

#1800 zh-trans: A New Logo for Jenkins X
  content/news/jenkins-x-new-logo.zh.md
Labels: needs-ok-to-test, size/M

#1807 fix: fixed typo in link to DCO image
  content/contribute/development.md
Labels: approved, lgtm, size/XS

#1811 Index update
  themes/gohugoioTheme/layouts/index.html
Labels: needs-ok-to-test, size/XL

#1812 Index update
  themes/gohugoioTheme/layouts/index.html
Labels: needs-ok-to-test, size/XL

#1813 New homepage
  themes/gohugoioTheme/layouts/index.html
  themes/gohugoioTheme/layouts/index_orig.html
Labels: size/S

#1821 docs: update next office hours
  content/community/_index.md
Labels: approved, size/XS

#1825 New homepage
  themes/gohugoioTheme/layouts/index.html
Labels: size/XS

#1826 New homepage
  themes/gohugoioTheme/layouts/index.html
Labels: size/XS

#1827 Homepage fix
  themes/gohugoioTheme/layouts/index.html
Labels: size/XS

#1828 Homepage fix
  themes/gohugoioTheme/layouts/index.html
Labels: size/XS

#1829 fix features overlap for smaller screens
  themes/gohugoioTheme/layouts/index.html
Labels: needs-ok-to-test, size/XS

#1830 add class for menu toggle
  themes/gohugoioTheme/layouts/index.html
Labels: needs-ok-to-test, size/XS

#1785 fix: use the new Flagger metric names
  content/developing/progressive-delivery.md
Labels: approved, lgtm, size/XS

#1832 feat: add instructions for using DNS whilst developing
  content/contribute/contribute_dns.md
Labels: approved, size/M

#1831 Chore: add a note about tests
  content/contribute/pullrequestreview.md
Labels: approved, size/XS

#1845 Adding an option to run Hugo server from a docker container
  README.md
  local.Dockerfile
Labels: size/S

#1847 Git server note
  content/developing/git.md
Labels: size/XS

#1852 docs: update office hours
  content/community/_index.md
Labels: approved, size/XS

#1858 docs: update link
  content/contribute/triage.md
Labels: approved, size/XS

#1859 Add new articles, add Mediums friend link URLs
  content/demos/articles.md
  content/faq/setup.md
Labels: approved, lgtm, ok-to-test, size/S

#1869 fix: lets use relative links
  themes/gohugoioTheme/layouts/index.html
Labels: approved, lgtm, size/S

#1870 fix: first spike at docs for lighthouse
  content/architecture/lighthouse.md
Labels: approved, lgtm, ok-to-test, size/L

#1871 fix: a bit more clarity on lighthouse versus jenkins x pipelines
  content/architecture/lighthouse.md
Labels: approved, lgtm, size/XS

#1862 chore: Add Dennis Newel as OWNER and REVIEWER
  OWNERS
Labels: approved, size/XS

#1850 docs: add to the pull request review tasks the security review and docs
  content/contribute/pullrequestreview.md
Labels: approved, size/S

#1837 docs: Viktor's articles and talks
  content/demos/articles.md
  content/demos/talks.md
Labels: approved, size/S

#1835 fix: add a note linking to external dns page
  content/contribute/contribute_dns.md
Labels: approved, ok-to-test

#1774 docs: fix syntax error in Terraform example
  content/getting-started/aws-terraform-install-gitops.md
Labels: approved, ok-to-test, size/XS

#1890 fix: polish boot docs
  content/getting-started/boot.md
Labels: approved, size/L
