Repository jenkins-x/jx-docs, pull requests merged in 2019-09, with the labels that each got.

#1873 docs: Jenkins World 2019 key takeaways blog post
  content/news/jenkinsworld-2019-takeaways.md
Labels: approved, lgtm, ok-to-test, size/L

#1861 initial run/fixing with the spell checker
  content/about/accelerate.md
  content/about/concepts.md
  content/about/decisions.md
  content/about/status.md
  content/about/what.md
  content/apps/worked-example.md
  content/architecture/access-control.md
  content/architecture/build-packs.md
  content/architecture/build-packs.zh.md
  content/architecture/cloud-native-jenkins.md
  content/architecture/components.md
  content/architecture/components.zh.md
  content/architecture/custom-jenkins.md
  content/architecture/dns.md
  content/architecture/docker-registry.md
  content/architecture/jenkins-x-pipelines.md
  content/architecture/pod-templates.md
  content/architecture/pod-templates.zh.md
  content/architecture/prow.md
Labels: size/L

#1864 feat: Adding tool to do spell checking incl. initial dictionary
  .spelling
  README.md
  docker-compose.yml
Labels: approved, lgtm, size/L

#1848 jenkins-x/jx#5163: updated Documentation Contribution page
  content/contribute/documentation.md
Labels: approved, lgtm, size/L

#1909 left nav structure in place
  content/en/docs/Contributing/Components.md
  content/en/docs/Contributing/Contribute-to-Docs.md
  content/en/docs/Contributing/Contribute-to-Jenkins-X.md
  content/en/docs/Contributing/Writing-addOns.md
  content/en/docs/Contributing/_index.md
  content/en/docs/Getting started/Setup Jenkins X/_index.md
  content/en/docs/Getting started/build-test-preview.md
  content/en/docs/Getting started/create-first-project.md
  content/en/docs/Getting started/demos-talks-posts.md
  content/en/docs/Getting started/installation.md
  content/en/docs/Getting started/promotion-and-environments copy.md
  content/en/docs/Managing Jenkins X/Examples/_index.md
  content/en/docs/Managing Jenkins X/Tasks/_index.md
  content/en/docs/Managing Jenkins X/Tutorials/_index.md
  content/en/docs/Managing Jenkins X/_index.md
  content/en/docs/Managing Jenkins X/faqs.md
  content/en/docs/Tasks/porridge.md
  content/en/docs/Tutorials/tutorial2.md
  content/en/docs/Using Jenkins X/Tasks/Import Apps/_index.md
  content/en/docs/Using Jenkins X/Tasks/_index.md
  content/en/docs/Using Jenkins X/Tasks/task.md
  content/en/docs/Using Jenkins X/_index.md
Labels: approved, lgtm, size/XL

#1912 docs: update office hours
  content/community/_index.md
Labels: approved, lgtm, size/XS

#1892 update Azure Kubernetes Service name
  content/commands/jx_create_cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#1910 docs: Fix broken url
  content/architecture/pod-templates.md
Labels: approved, lgtm, ok-to-test, size/XS

#1880 feat: add a section on TLS
  content/architecture/tls.md
Labels: approved, lgtm, size/S

#1939 feat: Added pre commit information
  content/contribute/development.md
Labels: approved, lgtm, size/XS

#1952 Remove weirdly encoded space that would mess with the markdown rendering
  content/faq/pipelines.md
Labels: approved, lgtm, ok-to-test, size/XS

#1962 fixed eks is _free_ bug.
  content/about/decisions.md
Labels: approved, lgtm, ok-to-test, size/XS

#1965 docs: update oh
  content/community/_index.md
Labels: size/XS

#1967 docs: update oh
  content/community/_index.md
Labels: approved, size/XS

#1963 fix: using version variable to generate updated urls for downloading jx
  content/getting-started/install.md
Labels: approved, lgtm, size/M

#1971 fix: add missing build pipeline step to install node dependencies
  jenkins-x.yml
Labels: size/XS

#1972 fix: try improve the folder structure a little bit
  README.md
  content/en/docs/Reference/api.md
  content/en/docs/Reference/devpods.md
  content/en/docs/Reference/pipeline-syntax-reference.md
  content/en/docs/using-jx/common-tasks/_index.md
  content/en/docs/using-jx/creating/_index.md
  content/en/docs/using-jx/creating/create-camel.md
  content/en/docs/using-jx/creating/create-mlquickstart.md
  content/en/docs/using-jx/creating/create-spring.md
  content/en/docs/using-jx/creating/import.md
  content/en/docs/using-jx/developing/_index.md
  content/en/docs/using-jx/developing/browsing.md
  content/en/docs/using-jx/developing/devpods.md
  content/en/docs/using-jx/developing/ide.md
  content/en/docs/using-jx/developing/issues.md
  content/en/docs/using-jx/developing/kube-context.md
  content/en/docs/using-jx/faq/_index.md
Labels: approved, lgtm, size/M

#1979 docs: update office hours
  content/en/community/events/_index.md
Labels: approved, lgtm, size/XS

#1984 fix: making banner image dynamically resize
  content/en/_index.html
Labels: approved, lgtm, size/XS

#1989 Removing console errors
  content/en/_index.html
  content/zh/_index.html
Labels: approved, lgtm

#1978 fix: sets theme-wide fonts
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: approved, lgtm, size/XS

#1992 fix: add alias for /docs/getting-started/install-on-cluster
  content/en/docs/managing-jx/common-tasks/install-on-cluster.md
Labels: approved, size/XS

#1994 Remove old admonitions and use docsy default instead
  content/en/blog/news/jenkins-x-observability.md
  content/en/blog/news/provision-jx-clusters-terraform.md
  content/en/docs/contributing/code/_index.md
  content/en/docs/contributing/documentation/_index.md
  content/en/docs/contributing/documentation/apidocs.md
  content/en/docs/getting-started/setup/install.md
  content/en/docs/managing-jx/common-tasks/git.md
  content/en/docs/managing-jx/common-tasks/install-on-cluster-what-happens.md
  content/en/docs/managing-jx/faq/issues.md
  content/en/docs/managing-jx/tutorials/install-gke-with-bot-tutorial.md
  content/en/docs/using-jx/developing/devpods.md
  content/zh/docs/contributing/code/_index.md
  content/zh/docs/contributing/documentation/_index.md
  content/zh/docs/contributing/documentation/apidocs.md
  content/zh/docs/managing-jx/common-tasks/install-on-cluster-what-happens.md
Labels: approved, lgtm, size/L

#2000 docs: Update _index.md
  content/en/docs/contributing/code/_index.md
Labels: approved, size/XS

#2008 feat: send "unhelpful" event category when someone clicks unhelpful button
  layouts/partials/feedback.html
Labels: approved, size/M

#2002 fix: Fix broken link in the Getting Started guide
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#1926 feat: Contributing builder images
  content/en/docs/contributing/code/builder-images.md
Labels: approved, size/L

#2011 fix: polish the navigation tree
  README.md
  content/en/docs/concepts/components.md
  content/en/docs/contributing/code/continuous-integrating-jx-itself.md
  content/en/docs/contributing/security.md
  content/en/docs/contributing/sponsors.md
  content/en/docs/getting-started/setup/boot.md
  content/en/docs/getting-started/setup/install.md
  content/en/docs/overview/accelerate.md
  content/en/docs/reference/components/_index.md
  content/en/docs/reference/components/build-packs.md
  content/en/docs/reference/components/cloud-native-jenkins.md
  content/en/docs/reference/components/custom-jenkins.md
  content/en/docs/reference/components/custom-resources.md
  content/en/docs/reference/components/docker-registry.md
  content/en/docs/reference/components/git.md
  content/en/docs/reference/components/helm3.md
  content/en/docs/reference/components/lighthouse.md
  content/en/docs/reference/components/pod-templates.md
  content/en/docs/reference/components/prow.md
  content/en/docs/reference/components/source.md
  content/en/docs/reference/components/vault.md
  content/en/docs/using-jx/faq/_index.md
  content/en/docs/using-jx/faq/pipelines.md
Labels: size/M

#2012 chore: external dns is recommended
  content/en/docs/contributing/code/contribute_dns.md
Labels: approved, lgtm, size/M

#2013 fix: added more modern getting started instructions using boot
  content/en/docs/getting-started/setup/boot/_index.md
  content/en/docs/getting-started/setup/boot/background.md
  content/en/docs/getting-started/setup/boot/how-it-works.md
  content/en/docs/getting-started/setup/create-cluster/_index.md
  content/en/docs/getting-started/setup/create-cluster/amazon.md
  content/en/docs/getting-started/setup/create-cluster/azure.md
  content/en/docs/getting-started/setup/create-cluster/google.md
  content/en/docs/getting-started/setup/install.md
  content/en/docs/getting-started/setup/old-create-cluster.md
  content/en/docs/managing-jx/examples/_index.md
  content/en/docs/using-jx/faq/_index.md
Labels: size/L

#2015 fix: lets move all deprecated docs into a folder
  content/en/docs/getting-started/setup/create-cluster/amazon/_index.md
  content/en/docs/getting-started/setup/create-cluster/amazon/terraform.md
  content/en/docs/managing-jx/common-tasks/dns.md
  content/en/docs/managing-jx/common-tasks/storage.md
  content/en/docs/managing-jx/common-tasks/tls.md
  content/en/docs/managing-jx/old/_index.md
  content/en/docs/managing-jx/old/config.md
  content/en/docs/managing-jx/old/create-cluster.md
  content/en/docs/managing-jx/old/install-on-cluster-what-happens.md
  content/en/docs/managing-jx/old/install-on-cluster.md
  content/en/docs/managing-jx/old/manage-via-gitops.md
Labels: size/M

#2014 docs: improve getting started instructions
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/M

#2017 docs: edit contribution guide
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/M

#2018 docs: edit instructions for making PR
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/M

#2010 docs: update link to Contribute page in different language versions
  content/en/_index.html
  content/zh/_index.html
Labels: approved, lgtm, ok-to-test, size/S

#2021 fix: move install into a subfolder to style like the other items at the same level
  content/en/docs/getting-started/setup/install/_index.md
Labels: approved, size/XS

#2004 Fix: Get Algolia search working again
  assets/scss/_variables_project.scss
  config.toml
  content/en/docs/reference/components/vault.md
  layouts/partials/head-css.html
  layouts/partials/scripts.html
  layouts/partials/search-input.html
  old/themes/gohugoioTheme/src/js/docsearch.js
  package-lock.json
  package.json
Labels: approved, size/XXL

#2022 fix: Add missing equals sign
  content/en/docs/reference/components/docker-registry.md
Labels: approved, ok-to-test, size/XS

#2024 docs: add a few helpful links
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/XS

#2025 docs: add image to 404 page
  layouts/404.html
  static/images/404-page/GOPHER RIDING REX.png
Labels: approved, size/XS

#2026 docs: update links in 404 page
  layouts/404.html
Labels: approved, size/XS

#2003 fix: Update Install jx instructions to auto-detect latest version
  content/en/docs/getting-started/setup/install/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2009 fix: remove old instructions from readme and link to docs page
  Localization_Chinese.md
  README.md
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/M

#1954 feat: Maturity levels
  content/en/about/maturity.md
Labels: approved, size/L

#2023 chore: bump dependencies including cleaning up package.json
  docker-compose.yml
  jenkins-x.yml
  package-lock.json
  package.json
Labels: approved, size/XL

#1930 contributing vault content back to OSS docs
  content/en/docs/reference/components/vault.md
Labels: approved, ok-to-test, size/L

#2028 chore: add documentation around algolia/docsearch
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/XS

#1997 fix: adding spring boot content from CJXD back to oss docs, take 2
  content/en/docs/using-jx/creating/create-spring.md
Labels: approved, lgtm, ok-to-test, size/L

#2029 fix: add hugo to the server command that starts local hugo
  docker-compose.yml
Labels: approved, size/XS

#2031 docs: add hacktoberfest blog
  content/en/blog/news/hacktoberfest-2019.md
  static/images/community/events/2019-hacktoberfest.png
Labels: approved, size/M

#2033 docs: fix date
  content/en/blog/news/hacktoberfest-2019.md
Labels: approved, size/XS

#2038 chore: adding footer link for signing up to k8s slack
  config.toml
Labels: approved, size/XS

#2040 fix: Remove placeholder text left behind from the theme
  content/en/docs/overview/_index.md
Labels: approved, size/XS

#2042 docs: add office hours
  content/en/blog/news/hacktoberfest-2019.md
Labels: approved, size/XS

#2037 fix: adding docs around running hugo locally
  .spelling
  content/en/docs/contributing/documentation/_index.md
  docker-compose.yml
Labels: approved, lgtm, size/L

#2046 added generic jenkins x newsletter subscription form
  content/en/community/newsletter.md
Labels: size/M

#2047 fix: correct instructions for using hugo server
  content/en/docs/contributing/documentation/_index.md
Labels: approved, size/S
