Repository jenkins-x/jx-docs, pull requests merged in 2020-02, with the labels that each got.

#2420 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2421 docs: add keynote to home page
  content/en/_index.html
Labels: approved, size/M

#2432 docs: add fosdem recap and talks blog
  content/en/blog/news/2020-fosdem-jx-talks.md
  static/images/community/events/fosdem_booth.jpg
Labels: approved, size/L

#2434 fix: command to to download the jx binary
  content/en/docs/managing-jx/old/create-cluster.md
Labels: approved, size/XS

#2433 docs: Add EKS IAM permissions overview from CJXD
  content/en/docs/getting-started/setup/boot/clouds/amazon.md
Labels: approved, size/L

#2440 docs: Add Vault section to EKS boot document
  content/en/docs/getting-started/setup/boot/clouds/amazon.md
Labels: approved, size/L

#2444 Pipelines
  content/en/docs/concepts/jenkins-x-pipelines.md
  content/en/docs/using-jx/faq/pipelines.md
  content/en/docs/using-jx/pipelines/_index.md
  content/en/docs/using-jx/pipelines/customimages.md
  content/en/docs/using-jx/pipelines/envvars.md
  content/en/docs/using-jx/pipelines/newpipeline.md
Labels: approved, size/L

#2450 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2422 fix: Update _index.md
  content/en/docs/concepts/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2423 fix: Update _index.md
  content/en/docs/contributing/documentation/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2443 feat: added package information to boot getting started guide
  content/en/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, size/S

#2451 docs: Add TLS and DNS instructions for booting to an EKS cluster
  content/en/docs/getting-started/setup/boot/clouds/amazon.md
Labels: approved, lgtm, size/M

#2454 chore: adding NOTE on setup of billing account.
  content/en/docs/getting-started/setup/create-cluster/google.md
Labels: size/XS

#2396 Updating various links pointing at older versions of builders
  content/en/docs/managing-jx/common-tasks/create-custom-builder.md
  content/en/docs/reference/components/pod-templates.md
  content/es/docs/managing-jx/common-tasks/create-custom-builder.md
  content/es/docs/reference/components/pod-templates.md
  content/zh/docs/managing-jx/common-tasks/create-custom-builder.md
  content/zh/docs/managing-jx/common-tasks/pod-templates.md
Labels: approved, ok-to-test, size/M

#2300 build: bumping hugo to 0.65.3. also switching to new htmltest image
  .htmltest.yml
  config.toml
  content/en/about/maturity.md
  content/en/blog/news/2020-fosdem-schedule.md
  content/en/blog/news/jenkins-x-observability.md
  content/en/blog/news/outreachy-december-2019.md
  content/en/blog/news/provision-jx-clusters-terraform.md
  content/en/community/office_hours/2019-02-21.md
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/code/_index.md
  content/en/docs/contributing/documentation/_index.md
  content/en/docs/contributing/documentation/apidocs.md
  content/en/docs/getting-started/setup/boot/_index.md
  content/en/docs/getting-started/setup/install/_index.md
  content/en/docs/managing-jx/common-tasks/storage.md
  content/en/docs/managing-jx/faq/_index.md
  content/en/docs/managing-jx/faq/boot.md
  content/en/docs/managing-jx/faq/issues.md
  content/en/docs/managing-jx/old/config.md
  content/en/docs/managing-jx/old/install-on-cluster-what-happens.md
  content/en/docs/overview/license.md
  content/en/docs/reference/components/git.md
  content/en/docs/reference/components/vault.md
  content/en/docs/using-jx/creating/create-camel.md
  content/en/docs/using-jx/developing/devpods.md
  content/en/docs/using-jx/faq/pipelines.md
  content/es/about/maturity.md
  content/es/docs/contributing/code/_index.md
  content/es/docs/contributing/documentation/_index.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/install/_index.md
  content/es/docs/managing-jx/faq/issues.md
  content/es/docs/reference/components/git.md
  content/es/docs/reference/components/vault.md
  content/zh/docs/Overview/license.md
  content/zh/docs/contributing/code/_index.md
  content/zh/docs/contributing/documentation/apidocs.md
  content/zh/docs/managing-jx/common-tasks/install-on-cluster-what-happens.md
  docker-compose.yml
  jenkins-x.yml
  layouts/shortcodes/pageinfo.html
Labels: approved, size/L

#2458 docs: feb 2020 blog for CJXD
  content/en/blog/news/cjxd-202002.md
  static/images/logo/cloudbees.png
Labels: approved, lgtm, size/M

#2459 docs: Remove duplicated content. Improve initial messaging. Grammar.
  content/en/docs/getting-started/setup/boot/clouds/amazon.md
Labels: approved, lgtm, size/L

#2430 chore: add helm resource already exists workaround
  content/en/docs/getting-started/setup/boot/clouds/on-premise.md
Labels: approved, ok-to-test, size/S

#2409 fix: Update components.md
  content/en/docs/concepts/components.md
Labels: approved, ok-to-test, size/XS

#2461 docs: blog about labs initiative
  content/en/blog/news/cjxd-202002.md
  content/en/blog/news/labs-202002.md
  static/images/logo/labs.png
Labels: approved, lgtm, size/M

#2467 docs: edit Community page
  content/en/community/_index.md
  static/images/community/GoCommunity-background.png
Labels: approved, size/S

#2469 docs: edit community page
  content/en/community/_index.md
Labels: approved, size/XS

#2449 feat: new page on using "edit this page" to submit changes
  content/en/docs/contributing/documentation/changes.md
  layouts/partials/page-meta-links.html
  static/images/contribute/commit_changes.png
  static/images/contribute/edit_page.png
  static/images/contribute/page_links.png
Labels: approved, size/M
