Repository jenkins-x/jx-docs, pull requests merged in 2020-12, with the labels that each got.

#3165 fix: add FAQ entry
  content/en/v3/admin/_index.md
  content/en/v3/develop/_index.md
  content/en/v3/develop/faq/_index.md
  static/images/developing/octant-step-click.png
  static/images/developing/octant-step.png
Labels: size/M

#3167 chore: project update for jx3 next steps moving out of alpha
  .lighthouse/jenkins-x/preview.yaml
  content/en/blog/news/2020-jx-v3-update.md
Labels: approved, size/M

#3166 fix: first spike at the pre-beta changes
  content/en/v3/about/changes.md
Labels: approved, lgtm, size/S

#3169 chore: no need to publish changelog for the website
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#3093 Update features.md
  content/en/about/concepts/features.md
Labels: needs-ok-to-test, size/XS

#3172 fix: add a few FAQ entries
  content/en/v3/develop/faq/_index.md
Labels: approved, size/M

#3173 fix: work around contributors build fail
  layouts/shortcodes/contributors.html
  layouts/shortcodes/contributors.json
Labels: size/XXL

#3177 fix: bit more polish on the blog
  content/en/blog/news/2020-jx-v3-beta.md
  content/en/v3/about/changes.md
Labels: size/S

#3171 docs: invalid path to .../git-operator/job.yaml
  content/en/v3/about/how-it-works.md
Labels: needs-ok-to-test, size/XS

#3174 fix(migration): add missing 'jx gitops repository export' doc link
  content/en/v3/admin/guides/migrate/v2.md
Labels: approved, lgtm, ok-to-test, size/XS

#3179 fix: add 3.x / 2.x links on home page
  content/en/_index.html
Labels: approved, size/XS

#3180 fix: lets add a troubleshooting section
  content/en/v3/admin/troubleshooting/_index.md
  content/en/v3/admin/troubleshooting/webhooks.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/M

#3182 docs: fix up Azure Terraform repo location
  content/en/v3/admin/platforms/azure.md
Labels: approved, lgtm, ok-to-test, size/XS

#3183 fix: added docs on extending quickstarts and catalogs
  content/en/v3/about/extending.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/M

#3184 fix: add redirect
  content/en/v3/about/how-it-works.md
Labels: size/XS

#3185 fix: add FAQ on webhooks
  content/en/v3/about/how-it-works.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/S

#3181 fix: updated maturity matrix for AWS, EKS, AKS
  static/images/v3/jx-v3alpha-maturity-matrix.png
Labels: size/XS

#3186 fix: improve jenkins help
  content/en/v3/admin/guides/jenkins/getting-started.md
Labels: approved, size/M

#3188 fix: polish links
  content/en/_index.html
  content/en/about/_index.md
  content/en/v3/about/_index.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/S

#3189 fix: add FAQ on bucket repo
  content/en/v3/develop/faq/_index.md
Labels: size/M
