Repository jenkins-x/jx-docs, pull requests merged in 2020-11, with the labels that each got.

#3109 chore: fix blocker sonarcloud issues
  content/en/_index.html
  content/zh/_index.html
  layouts/shortcodes/calendar.html
  static/css/terminal.css
Labels: approved, lgtm, size/S

#3118 fix: add OpenShift docs
  content/en/docs/v3/_index.md
  content/en/docs/v3/getting-started/minikube.md
  content/en/docs/v3/getting-started/on-premise.md
  content/en/docs/v3/getting-started/openshift.md
  content/en/docs/v3/guides/infra/minikube.md
  content/en/docs/v3/guides/infra/openshift-crc.md
  static/images/logo/openshift.png
Labels: approved, lgtm, size/L

#3122 fix: add FAQ entry
  content/en/docs/v3/develop/faq/_index.md
Labels: size/M

#3123 fix: add better extensions docs
  content/en/docs/v3/about/extending.md
  content/es/blog/_index.md
Labels: approved, size/M

#3129 fix: add better list of missing features
  content/en/blog/news/2020-accelerate-tekton.md
Labels: size/XS

#3130 fix: polish the infra guides page
  content/en/docs/v3/guides/infra/_index.md
  content/en/docs/v3/guides/operator.md
Labels: size/S

#3131 fix: add FAQ on helmfile template
  content/en/docs/v3/develop/faq/_index.md
Labels: size/M

#3136 fix: use a nicer URL for v3
  config.toml
  content/en/v3/_index.md
  content/en/v3/about/_index.md
  content/en/v3/about/benefits.md
  content/en/v3/about/changes.md
  content/en/v3/about/comparison.md
  content/en/v3/about/extending.md
  content/en/v3/about/how-it-works.md
  content/en/v3/about/maturity-matrix.md
  content/en/v3/about/overview.md
  content/en/v3/about/what.md
  content/en/v3/develop/_index.md
  content/en/v3/develop/apps.md
  content/en/v3/develop/create-project/_index.md
  content/en/v3/develop/create-project/jenkinsfile.md
  content/en/v3/develop/faq/_index.md
  content/en/v3/develop/pipeline-catalog.md
  content/en/v3/develop/ui/_index.md
  content/en/v3/develop/ui/cli.md
  content/en/v3/develop/ui/dashboard.md
  content/en/v3/develop/ui/octant.md
  content/en/v3/getting-started/_index.md
  content/en/v3/getting-started/azure.md
  content/en/v3/getting-started/eks.md
  content/en/v3/getting-started/gke.md
  content/en/v3/getting-started/minikube.md
  content/en/v3/getting-started/on-premise.md
  content/en/v3/getting-started/openshift.md
  content/en/v3/guides/_index.md
  content/en/v3/guides/config.md
  content/en/v3/guides/health.md
  content/en/v3/guides/infra/_index.md
  content/en/v3/guides/infra/cloud-config.md
  content/en/v3/guides/infra/google_cloud_dns.md
  content/en/v3/guides/infra/minikube.md
  content/en/v3/guides/infra/openshift-crc.md
  content/en/v3/guides/infra/tls_dns.md
  content/en/v3/guides/jenkins/_index.md
  content/en/v3/guides/jenkins/getting-started.md
  content/en/v3/guides/jenkins/importing.md
  content/en/v3/guides/jx3.md
  content/en/v3/guides/migrate.md
  content/en/v3/guides/multi-cluster.md
  content/en/v3/guides/operator.md
  content/en/v3/guides/progressive-delivery.md
  content/en/v3/guides/secrets/_index.md
  content/en/v3/guides/secrets/vault.md
  content/en/v3/guides/upgrade.md
Labels: size/S

#3138 feat: added PR template for submitters
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#3139 docs: improve dns and tls docs, giving clearer guidance and explaination, also contains example for enabling TLS in previews
  content/en/v3/admin/guides/infra/tls_dns.md
  static/images/v3/working_tls.png
Labels: approved, lgtm, size/L

#3140 docs: FaQ on avoiding namespaceSubdomain
  content/en/v3/admin/guides/infra/tls_dns.md
Labels: approved, lgtm, size/XS

#3142 fix: simpler layout for admin
  content/en/v3/admin/guides/config.md
  content/en/v3/admin/guides/infra/_index.md
  content/en/v3/admin/guides/infra/cloud-config.md
  content/en/v3/admin/guides/tls_dns.md
  content/en/v3/admin/platforms/google/_index.md
  content/en/v3/admin/platforms/google/cloud_dns.md
  content/en/v3/admin/platforms/minikube.md
  content/en/v3/admin/platforms/minikube/_index.md
  content/en/v3/admin/platforms/openshift/_index.md
  content/en/v3/admin/platforms/openshift/openshift-crc.md
Labels: size/L

#3143 chore: more pipeline fixes
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S

#3144 chore: enable v3 previews
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/triggers.yaml
  charts/preview/Makefile
  charts/preview/helmfile.yaml
  charts/preview/templates/deployment.yaml
  charts/preview/templates/ingress.yaml
  charts/preview/values.yaml
  charts/preview/values.yaml.gotmpl
Labels: approved, size/L

#3148 chore: lets use the wildcard cert from the jx namespace
  README.md
  charts/preview/helmfile.yaml
  charts/preview/templates/ingress.yaml
  content/en/v3/admin/guides/tls_dns.md
Labels: approved, size/M

#3146 fix(menu): expand sidebar menu by default
  config.toml
Labels: approved, lgtm, ok-to-test, size/XS

#3145 fix(sidebar): remove sidebar searchbox
  assets/scss/_sidebar-tree.scss
Labels: size/S

#3152 docs: fix TLS docs after switching nginx to use a default cert
  content/en/v3/admin/guides/tls_dns.md
Labels: approved, lgtm, size/S

#3153 fix: Expand only "About" menu section when opening v3 doc
  config.toml
Labels: approved, lgtm, ok-to-test, size/XS

#3154 fix: add the develop+admin cards to the docs
  content/en/v3/about/_index.md
Labels: size/XS

#3155 chore: minor edit to create project docs
  content/en/v3/develop/create-project/_index.md
Labels: approved, lgtm, size/XS

#3156 refactor: minor edits to the landing page
  content/en/_index.html
Labels: approved, lgtm, size/XS

#3157 fix: polish the multi cluster docs
  content/en/v3/admin/guides/multi-cluster.md
Labels: size/M

#3111 docs: Update _index.md
  content/en/about/_index.md
Labels: needs-ok-to-test, size/XS

#3159 fix: add a projects and source pages
  content/en/v3/about/overview/_index.md
  content/en/v3/about/overview/projects.md
  content/en/v3/about/overview/source.md
Labels: size/M

#3160 fix: added links for tekton and lighthouse
  content/en/v3/about/overview/projects.md
Labels: approved, size/XS

#3161 fix: add jenkins link
  content/en/v3/about/overview/projects.md
  content/en/v3/admin/guides/jenkins/_index.md
Labels: approved, size/XS

#3162 docs: add docs on how to track teh upgrade from a boot job
  content/en/v3/admin/guides/upgrade.md
Labels: approved, size/XS
