Repository jenkins-x/jx-docs, pull requests merged in 2020-07, with the labels that each got.

#2955 docs: JX Open Innovation blog post
  content/en/blog/news/2020-jx-open-innovation.md
Labels: approved, lgtm, size/M

#2958 fix: change feedback section link to point to jx-docs issue section
  config.toml
Labels: approved, lgtm, size/XS

#2956 docs: add consolidate addons and apps coding phase 1 blog post
  content/en/blog/news/2020-gsoc-consolidate-addons-and-apps-phase-1.md
Labels: approved, lgtm, ok-to-test, size/M

#2957 fix: remove highlightjs and use chroma
  Makefile
  assets/scss/_code.scss
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  config.toml
  content/en/community/documentation/reference.md
  content/en/docs/install-setup/create-cluster/eks.md
  content/en/docs/install-setup/create-cluster/gke.md
  content/en/docs/labs/boot/getting-started/cloud/gcloud.md
  docker-compose.yml
  jenkins-x.yml
  layouts/partials/scripts.html
Labels: approved, lgtm, size/L

#2962 fix: change HUGO_VERSION to fix build issues
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#2963 fix: attempt to fix master build
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#2964 fix: password typo
  content/en/docs/reference/components/docker-registry.md
Labels: approved, lgtm, ok-to-test, size/XS

#2968 docs: add Ankit to owners file
  OWNERS
Labels: size/XS

#2936 feat: First pass of Style Guide
  content/en/community/documentation/style-guide.md
Labels: size/M

#2950 feat: Added link to Pluralsight course
  content/en/docs/resources/tutorials/pluralsight.md
Labels: approved, lgtm, ok-to-test, size/S

#2979 refactor: remove references to jenkinsX oss alternatives
  content/en/_index.html
  content/en/docs/_index.html
  content/en/docs/alternatives.html
  content/en/docs/install-setup/create-cluster/_index.md
  content/es/_index.html
Labels: approved, lgtm, size/L

#2975 fix: change broken external link to an internal link
  content/en/docs/install-setup/install-binary/_index.md
Labels: approved, lgtm, size/XS

#2980 refactor: remove ide sections which lead to broken external links
  content/en/docs/build-test-preview/devpods.md
  content/en/docs/reference/devpods.md
  content/en/docs/resources/guides/using-jx/developing/ide.md
Labels: approved, lgtm, size/M

#2977 fix: #2982 correct the "install Jenkins X" link
  content/en/about/concepts/features.md
Labels: approved, lgtm, ok-to-test, size/XS

#2983 docs: add consolidate addons and apps coding phase 2 doc
  content/en/blog/news/2020-gsoc-consolidate-addons-and-apps-phase-2.md
Labels: approved, lgtm, ok-to-test, size/M

#2985 docs: add a blog on moving from CJXD to upstream JX
  content/en/blog/news/2020-cjxd-upstreamjx-future.md
Labels: approved, lgtm, size/M

#2986 docs: add discourse embed
  content/en/blog/news/fosdem-2020.md
Labels: approved, lgtm, size/S

#2988 docs: remove sub project explanation
  content/en/docs/resources/faq/general.md
Labels: approved, size/S

#2989 docs: remove reference to previous UI
  content/en/docs/resources/faq/config.md
Labels: approved, lgtm, size/XS

#2996 docs: update ui info
  content/en/docs/resources/faq/config.md
Labels: approved, lgtm, size/XS

#2999 docs: add help for stuck install
  content/en/docs/resources/faq/setup.md
Labels: approved, lgtm, ok-to-test, size/S
