Repository jenkins-x/jx-docs, pull requests merged in 2020-03, with the labels that each got.

#2472 fix: Update pipeline-syntax-reference.md
  content/en/docs/reference/pipeline-syntax-reference.md
Labels: approved, lgtm, ok-to-test, size/XS

#2462 fix: updated diagram page with new diagram for tekton+lighthouse
  content/en/docs/concepts/diagram.md
  static/images/ArchitectureServerlessJenkins.drawio
  static/images/ArchitectureServerlessJenkinsLighthouse.png
Labels: approved, lgtm, size/S

#2474 fix: polish labs boot docs
  content/en/docs/labs/boot/benefits.md
  content/en/docs/labs/boot/faq/_index.md
  content/en/docs/labs/boot/getting-started.md
  content/en/docs/labs/boot/getting-started/config.md
  content/en/docs/labs/boot/getting-started/secrets.md
  content/en/docs/labs/boot/tips.md
  content/en/docs/labs/jxl.md
  content/en/docs/reference/multi-cluster.md
Labels: approved, lgtm, size/XL

#2479 fix: polish the helm 3 boot cloud resources docs
  content/en/docs/labs/boot/getting-started/cloud.md
  content/en/docs/labs/boot/getting-started/cloud/_index.md
  content/en/docs/labs/boot/getting-started/cloud/gcloud.md
  content/en/docs/labs/boot/getting-started/cloud/terraform.md
  content/en/docs/labs/boot/getting-started/repository.md
Labels: approved, size/L

#2481 fix: polish docs
  content/en/docs/labs/jenkins/importing.md
Labels: approved, size/S

#2482 fix: ensure latest enhancements
  jenkins-x.yml
  update-content.sh
Labels: approved, size/S

#2488 fix: polish multi cluster docs
  content/en/docs/labs/boot/getting-started/cloud/gcloud.md
  content/en/docs/labs/boot/multi-cluster.md
Labels: approved, size/M

#2496 docs: Make time information for office hours more accessible
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2497 fix: polish docs
  content/en/docs/labs/boot/getting-started/repository.md
  content/en/docs/labs/boot/multi-cluster.md
Labels: approved, size/S

#2499 fix: add new FAQ entry on helm3 and TLS
  content/en/docs/labs/boot/faq/_index.md
Labels: approved, size/S

#2498 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2504 docs: blog and demo on google secrets manager
  content/en/blog/news/gsm-controller.md
  static/images/logo/secret-manager.png
Labels: approved, size/M

#2507 docs: add office hours recordings
  content/en/blog/news/gsm-controller.md
  content/en/community/office_hours/2020-01-23.md
  content/en/community/office_hours/2020-03-05.md
Labels: approved, size/M

#2513 docs: modify description of Jenkins X pipelines
  content/en/docs/concepts/jenkins-x-pipelines/_index.md
Labels: approved, size/S

#2386 docs: walkthrough tutorial
  content/en/blog/news/walkthrough.md
Labels: approved, size/L

#2518 fix: edits on walkthrough
  content/en/blog/news/walkthrough.md
Labels: approved, size/XS

#2523 docs: add Tekton blog post
  content/en/blog/news/jenkins-x-tekton.md
Labels: approved, size/M

#2525 fix: polish jenkins interop docs
  content/en/docs/labs/jenkins/getting-started.md
Labels: approved, size/XS

#2524 docs: add contact link
  content/en/blog/news/jenkins-x-tekton.md
Labels: approved, lgtm, size/XS

#2526 docs: add mailto email link
  content/en/blog/news/jenkins-x-tekton.md
Labels: approved, size/XS

#2527 fix: add docs on shrinking footprint
  content/en/docs/labs/boot/getting-started/repository.md
Labels: approved, size/S

#2530 chore: Presentation newsletter pop
  .vscode/settings.json
  content/en/_index.html
  layouts/partials/scripts.html
Labels: size/S

#2531 feat: moved presentation to resources new section
  content/en/_index.html
  content/en/docs/artwork/_index.md
Labels: size/S

#2533 chore: Resources section on left nav
  content/en/docs/contributing/_index.md
Labels: size/XS

#2534 chore: reverted to artwork node left nav
  content/en/docs/artwork/_index.md
Labels: size/S

#2494 feat: Add section on recreating cluster with same name
  content/en/docs/managing-jx/faq/issues.md
Labels: approved, lgtm, size/S

#2544 feat: Added documentation for MLOps
  content/en/docs/mlops/_index.md
  content/en/docs/mlops/data.md
  content/en/docs/mlops/gpu.md
  content/en/docs/mlops/introduction.md
  content/en/docs/mlops/mlquickstarting.md
  content/en/docs/mlops/mlquickstarts.md
Labels: approved, lgtm, size/L

#2546 fix: polish docs on switching out nginx for istio
  content/en/docs/concepts/_index.md
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/demos-talks-posts/talks.md
  content/en/docs/labs/boot/benefits.md
  content/en/docs/labs/boot/getting-started/repository.md
  content/en/docs/mlops/_index.md
  content/en/docs/mlops/data.md
  content/en/docs/mlops/gpu.md
  content/en/docs/mlops/introduction.md
  content/en/docs/mlops/mlquickstarting.md
  content/en/docs/mlops/mlquickstarts.md
  content/en/docs/using-jx/creating/create-mlquickstart.md
Labels: approved, size/M

#2538 chore: fixed typo in jxl --env-remote argument
  content/en/docs/labs/boot/multi-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#2543 Correct headline levels in git.md
  content/en/docs/reference/components/git.md
Labels: approved, lgtm, ok-to-test, size/XS

#2552 fix: add a first spike at how to use progressive delivery
  content/en/docs/labs/boot/apps.md
  content/en/docs/labs/boot/background.md
  content/en/docs/labs/boot/benefits.md
  content/en/docs/labs/boot/comparison.md
  content/en/docs/labs/boot/how-it-works.md
  content/en/docs/labs/boot/progressive-delivery.md
Labels: approved, size/L

#2547 docs: Updating the README
  LICENSE.md
  Makefile
  README.md
Labels: approved, lgtm, size/L

#2549 refactor: moving ci scripts into subdirectory
  jenkins-x.yml
  local.Dockerfile
  requirements.txt
  scripts/ci/changelog.sh
  scripts/ci/update-content.sh
  scripts/ci/update-website.sh
  scripts/deploy.sh
  scripts/pull-theme.sh
Labels: approved, lgtm, size/S

#2556 fix: add FAQ entry for Jenkins
  content/en/docs/labs/jenkins/faq/_index.md
Labels: approved, lgtm, size/S

#2558 fix: typo
  content/en/docs/labs/boot/progressive-delivery.md
Labels: approved, size/XS

#2557 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, lgtm, size/XS

#2559 fix: add note about commenting out jxui
  content/en/docs/labs/boot/progressive-delivery.md
Labels: size/XS

#2562 docs: edit image credit
  content/en/blog/news/outreachy-december-2019.md
Labels: approved, lgtm, size/XS

#2563 docs: add Marky Jackson to repo owners
  OWNERS
Labels: approved, lgtm, size/XS

#2568 docs: add buttons to make navigating labs getting started steps easier
  content/en/docs/labs/boot/getting-started/cloud/gcloud.md
  content/en/docs/labs/boot/getting-started/config.md
  content/en/docs/labs/boot/getting-started/repository.md
  content/en/docs/labs/boot/getting-started/run.md
  content/en/docs/labs/boot/getting-started/secrets.md
  content/en/docs/labs/jxl.md
Labels: approved, lgtm, size/M

#2572 feat: add some basic connectivity requirements
  content/en/docs/managing-jx/common-tasks/connectivity.md
Labels: approved, lgtm, size/M

#2574 chore: changing verbiage on getting started landing page
  content/en/docs/_index.md
Labels: approved, lgtm, size/XS

#2495 feat: Add instructions for debugging jx boot pipeline
  content/en/docs/contributing/code/_index.md
Labels: approved, lgtm, size/S

#2588 docs: gsoc blog post
  content/en/blog/news/2020-gsoc.md
  static/images/community/events/GSoC-logo.png
Labels: approved, lgtm, size/M

#2583 fix: update broken link
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS
