Repository jenkins-x/jx-docs, pull requests merged in 2020-10, with the labels that each got.

#3079 feat: jx v3 maturity model matrix
  content/en/docs/v3/about/maturity-matrix.md
  static/images/v3/jx-v3alpha-color-rep.png
  static/images/v3/jx-v3alpha-maturity-matrix.png
Labels: approved, lgtm, size/S

#3087 docs: add note to maturity matrix to highlight it relates to Jenkins X alpha
  content/en/docs/v3/about/maturity-matrix.md
Labels: approved, lgtm, size/XS

#3088 feat: added maturity matrix for post JX v3 GA release
  content/en/docs/v3/about/maturity-matrix.md
  static/images/v3/jx-v3ga-maturity-matrix.png
Labels: approved, lgtm, size/XS

#3085 refactor: replace eks create cluster section with readme
  content/en/docs/_index.html
  content/en/docs/install-setup/create-cluster/_index.md
  content/en/docs/install-setup/create-cluster/aks.md
  content/en/docs/install-setup/create-cluster/eks.md
  content/en/docs/install-setup/create-cluster/gke.md
Labels: approved, lgtm, size/XL

#3077 Update secrets.md
  content/en/docs/install-setup/boot/secrets.md
Labels: approved, lgtm, ok-to-test, size/XS

#3094 fix: add more 3.x links
  content/en/docs/reference/components/source.md
Labels: approved, size/M

#3095 fix: add upgrade strategy docs
  content/en/docs/v3/guides/upgrade.md
Labels: approved, size/S

#3090 docs: how to change strategy for jx gitops upgarde
  content/en/docs/v3/guides/upgrade.md
Labels: ok-to-test, size/XS

#3099 docs: add health docs
  content/en/docs/v3/guides/health.md
Labels: approved, lgtm, size/M

#3101 fix: improve the docs around creating a git token
  content/en/docs/v3/getting-started/on-premise.md
  content/en/docs/v3/guides/infra/minikube.md
  content/en/docs/v3/guides/operator.md
Labels: approved, size/M

#3103 fix: improve the docs around pipeline catalogs
  content/en/docs/v3/about/changes.md
  content/en/docs/v3/guides/pipeline-catalog.md
Labels: approved, size/M

#3107 fix: make the rectangles the same height
  content/en/docs/v3/_index.md
Labels: size/S

#3108 fix: improve upgrade docs
  content/en/docs/v3/guides/upgrade.md
Labels: size/S

#3110 refactor: change the quickstart repo for eks
  content/en/docs/v3/getting-started/eks.md
Labels: approved, lgtm, size/XS
