Repository jenkins-x/jx-docs, pull requests merged in 2020-08, with the labels that each got.

#3003 chore: add terraform debug information to faqs
  content/en/docs/resources/faq/setup.md
Labels: approved, lgtm, size/XS

#2994 chore: add documentation around nat gateways and velero backups
  content/en/docs/install-setup/create-cluster/eks.md
Labels: approved, lgtm, size/M

#3005 docs: add info on discourse
  content/en/community/_index.md
Labels: approved, lgtm, size/S

#3001 feat(pipelines): document new support for Tekton Sidecar containers
  content/en/docs/reference/pipeline-syntax-reference.md
Labels: approved, lgtm, ok-to-test, size/XS

#3013 chore: add debugging information
  content/en/docs/install-setup/boot/_index.md
  content/en/docs/resources/faq/setup.md
Labels: approved, lgtm, size/M

#3017 docs: update roadmap
  content/en/community/roadmap.md
Labels: approved, lgtm, size/S

#3019 fix: improve operator docs
  content/en/docs/v3/guides/operator.md
Labels: approved, size/S

#3020 docs: add how to get the new jx3 alpha CLI commands
  content/en/docs/v3/getting-started/_index.md
Labels: approved, lgtm, size/S

#3021 docs: edit buttons
  content/en/_index.html
Labels: approved, lgtm, size/XS

#3022 docs: tiny edits
  content/en/docs/resources/faq/using/chatops.md
Labels: approved, lgtm, size/XS

#3023 fix: first spike at minikube instructions
  content/en/docs/v3/guides/infra/_index.md
  content/en/docs/v3/guides/infra/minikube.md
Labels: approved, lgtm, size/M

#3027 fix: add upgrade docs
  content/en/docs/v3/guides/upgrade.md
Labels: approved, size/S

#3032 docs: add official apps repository section
  content/en/docs/resources/guides/extending-jx/apps.md
Labels: approved, lgtm, ok-to-test, size/XS

#3007 docs: update FAQ on secrets management
  content/en/docs/resources/faq/using/_index.md
Labels: approved, lgtm, size/XS

#3035 fix: tell minikube to use VM
  content/en/docs/v3/guides/infra/minikube.md
Labels: approved, lgtm, ok-to-test, size/XS

#3036 fix: minikube instructions
  content/en/docs/v3/guides/infra/minikube.md
Labels: approved, lgtm, size/XS

#3026 feat: docs for running jx3 on eks
  content/en/docs/v3/getting-started/_index.md
  content/en/docs/v3/getting-started/eks.md
  content/en/docs/v3/getting-started/gke.md
Labels: approved, lgtm, size/L

#3039 fix: add a minikube page
  content/en/docs/v3/getting-started/minikube.md
Labels: approved, size/S

#3033 fix: fix docs navbar to top
  assets/scss/_sidebar-tree.scss
  layouts/partials/navbar.html
  static/css/style.css
Labels: approved, do-not-merge/hold, lgtm, ok-to-test, size/S

#3038 fix: creation of Issue Templates for users reference
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, ok-to-test, size/M
