Repository jenkins-x/jx-docs, pull requests merged in 2020-09, with the labels that each got.

#3042 preview environment creation details are incorrect
  content/en/docs/build-test-preview/preview.md
Labels: approved, lgtm, ok-to-test, size/XS

#3043 fix: build pack pipeline file name
  content/en/docs/build-test-preview/jenkins-x-pipelines/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#3047 docs: clarify JX CLI installation
  content/en/docs/v3/getting-started/_index.md
Labels: approved, lgtm, size/XS

#3050 docs: add link for info on installing/using Octant
  content/en/blog/news/2020-octant-jx.md
Labels: approved, lgtm, size/XS

#3052 docs: add easier dco signoff
  content/en/community/code/_index.md
Labels: approved, lgtm, size/M

#3059 docs: Create 2020-cdcon.md
  content/en/blog/news/2020-cdcon.md
  static/images/cdcon-register.png
Labels: approved, lgtm, ok-to-test, size/M

#3061 docs: more Jenkins X 3.x docs
  content/en/docs/v3/_index.md
  content/en/docs/v3/about/_index.md
  content/en/docs/v3/about/overview.md
  content/en/docs/v3/about/upgrading.md
  content/en/docs/v3/getting-started/_index.md
  content/en/docs/v3/getting-started/eks.md
  content/en/docs/v3/getting-started/gke.md
  content/en/docs/v3/getting-started/minikube.md
  static/images/v3/overview.png
Labels: approved, lgtm, size/L

#3063 docs: lets try and embed the whimsical to see if hyperlinks still work
  content/en/docs/v3/about/overview.md
Labels: approved, lgtm, size/XS

#3064 fix: mention alpha in the blog title
  content/en/blog/news/2020-jx-v3.md
Labels: approved, lgtm, size/XS

#3066 docs: add GCP + Terraform getting started demo
  content/en/docs/v3/getting-started/gke.md
Labels: approved, lgtm, size/XS

#3067 fix: remove the old quickstart
  content/en/docs/v3/getting-started/gke.md
Labels: approved, lgtm, size/S

#3070 fix: add migrate docs
  content/en/docs/v3/guides/apps.md
  content/en/docs/v3/guides/faq/_index.md
  content/en/docs/v3/guides/jenkins/_index.md
  content/en/docs/v3/guides/migrate.md
Labels: approved, size/M

#3065 docs: edits to JX 3 Getting Started
  content/en/docs/v3/getting-started/_index.md
Labels: approved, lgtm, size/S

#3074 docs: hacktoberfest blog post
  content/en/blog/news/2020-hacktoberfest.md
  static/images/community/events/2020-hacktoberfest.jpg
Labels: approved, lgtm, size/M

#3073 docs: add blog post for the jx-pipelines-visualizer
  content/en/blog/news/2020-pipelines-visualizer.md
Labels: approved, lgtm, ok-to-test, size/M

#3075 fix(blog): fix the size of the embedded youtube video
  content/en/blog/news/2020-pipelines-visualizer.md
Labels: approved, lgtm, ok-to-test, size/XS

#3076 fix: added how to install minikube for users of windows 10 home as hyper-v…
  content/en/docs/v3/guides/infra/minikube.md
Labels: approved, lgtm, ok-to-test, size/S

#3078 docs: minor changes in jx 3 docs
  content/en/docs/v3/about/benefits.md
  content/en/docs/v3/about/comparison.md
  content/en/docs/v3/about/how-it-works.md
  content/en/docs/v3/about/overview.md
  content/en/docs/v3/create-project/_index.md
  content/en/docs/v3/getting-started/_index.md
  content/en/docs/v3/guides/apps.md
  content/en/docs/v3/guides/config.md
  content/en/docs/v3/guides/jx3.md
  content/en/docs/v3/guides/migrate.md
  content/en/docs/v3/guides/operator.md
  content/en/docs/v3/guides/progressive-delivery.md
  content/en/docs/v3/guides/upgrade.md
Labels: approved, lgtm, size/M

#3081 fix: remove legacy from the Jenkins guide
  content/en/docs/v3/guides/jenkins/_index.md
  content/en/docs/v3/guides/jenkins/faq/_index.md
  content/en/docs/v3/guides/jenkins/getting-started.md
  content/en/docs/v3/guides/jenkins/importing.md
  content/en/docs/v3/guides/jenkins/overview.md
Labels: approved, lgtm, size/L
