Repository jenkins-x/jx-docs, pull requests merged in 2020-04, with the labels that each got.

#2595 chore: updating and restructuring the contributing to docs pages
  Makefile
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/code/_index.md
  content/en/docs/contributing/documentation/_index.md
  content/en/docs/contributing/documentation/apidocs.md
  content/en/docs/contributing/documentation/changes.md
  content/en/docs/contributing/documentation/reference.md
  content/en/docs/contributing/documentation/step-by-step.md
  content/en/docs/contributing/documentation/workflow.md
  content/en/docs/contributing/sponsors.md
Labels: approved, lgtm, size/XL

#2598 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, lgtm, size/XS

#2607 chore: Add daveconde to owners
  OWNERS
Labels: approved, lgtm, size/XS

#2604 fix: fixed typo in filename jx-requirements.yml
  content/en/docs/getting-started/setup/create-cluster/gke.md
Labels: approved, lgtm, size/XS

#2609 chore: updating Terraform in- and output variables
  content/en/docs/getting-started/setup/create-cluster/gke.md
Labels: approved, lgtm

#2613 fix: updated typo and adjusted grammar on getting started pages - creating a cluster
  content/en/docs/getting-started/setup/create-cluster/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2618 fix: updated a typo in overview/_index.md
  content/en/docs/overview/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2625 docs: add apostrophe
  content/en/docs/getting-started/first-project/create-quickstart.md
Labels: approved, lgtm, ok-to-test, size/XS

#2629 chore: update deprecation list
  content/en/docs/reference/commands/deprecation.md
Labels: approved, lgtm, size/XS

#2643 docs: Update serverless.md Corrected `Coontinuous` with `Continuous`.
  content/en/blog/news/serverless.md
Labels: approved, lgtm, ok-to-test, size/XS

#2640 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, lgtm, size/S

#2659 docs: Remove JX with Jenkins static masters diagram
  content/en/docs/concepts/diagram.md
Labels: approved, lgtm, size/S

#2654 fix: updating documentation around using the GKE and EKS Terraform mo…
  content/en/docs/getting-started/setup/create-cluster/eks.md
  content/en/docs/getting-started/setup/create-cluster/gke.md
Labels: approved, lgtm, size/L

#2660 docs: remove reference to Jenkins
  content/en/docs/concepts/features.md
Labels: approved, lgtm, size/XS

#2665 fix: move output outside of module
  content/en/docs/getting-started/setup/create-cluster/eks.md
Labels: approved, lgtm, size/S

#2669 chore: OWNERS file update and cleanup
  OWNERS
Labels: approved, lgtm, size/M

#2682 fix: redirect for /docs
  config.toml
  content/en/docs/getting-started/_index.html
Labels: approved, lgtm, size/S

#2666 fix: homepage revision
  config.toml
  content/en/_index.html
  layouts/partials/footer.html
Labels: approved, lgtm, size/L

#2653 docs: Update tls.md
  content/en/docs/guides/managing-jx/common-tasks/tls.md
Labels: approved, lgtm, size/S

#2712 chore: adding setup section to left nav
  content/en/docs/getting-started/setup/_index.md
Labels: size/S

#2713 fix: link color within bootstrap alerts
  assets/scss/_styles_project.scss
Labels: size/XS
