Repository jenkins-x/jx-docs, pull requests merged in 2020-01, with the labels that each got.

#2311 fix: update broken links to cli commands
  content/en/blog/news/serverless-jenkins.md
  content/en/blog/releases/changes-11-april-2018.md
  content/en/blog/releases/changes-27-april-2018.md
  content/en/docs/concepts/features.md
  content/en/docs/concepts/jenkins-x-pipelines.md
  content/en/docs/concepts/version-stream.md
  content/en/docs/getting-started/demos-talks-posts/create_cluster.md
  content/en/docs/getting-started/demos-talks-posts/create_spring.md
  content/en/docs/getting-started/first-project/create-quickstart.md
  content/en/docs/getting-started/setup/boot/background.md
  content/en/docs/managing-jx/faq/_index.md
  content/en/docs/managing-jx/faq/issues.md
  content/en/docs/managing-jx/old/config.md
  content/en/docs/managing-jx/old/create-cluster.md
  content/en/docs/managing-jx/old/install-on-cluster.md
  content/en/docs/managing-jx/old/manage-via-gitops.md
  content/en/docs/managing-jx/tutorials/serverless-apps.md
  content/en/docs/overview/changelog.md
  content/en/docs/reference/commands/_index.md
  content/en/docs/reference/components/custom-jenkins.md
  content/en/docs/reference/components/git.md
  content/en/docs/reference/components/pod-templates.md
  content/en/docs/reference/multi-cluster.md
  content/en/docs/using-jx/creating/create-camel.md
  content/en/docs/using-jx/creating/create-mlquickstart.md
  content/en/docs/using-jx/creating/import.md
  content/en/docs/using-jx/developing/browsing.md
  content/en/docs/using-jx/faq/pipelines.md
  content/es/docs/concepts/features.md
  content/es/docs/concepts/jenkins-x-pipelines.md
  content/es/docs/concepts/version-stream.md
  content/es/docs/getting-started/demos-talks-posts/create_cluster.md
  content/es/docs/getting-started/demos-talks-posts/create_spring.md
  content/es/docs/getting-started/first-project/create-quickstart.md
  content/es/docs/getting-started/setup/boot/_index.md
  content/es/docs/getting-started/setup/boot/background.md
  content/es/docs/managing-jx/faq/_index.md
  content/es/docs/managing-jx/faq/issues.md
  content/es/docs/reference/components/custom-jenkins.md
  content/es/docs/reference/components/git.md
  content/es/docs/reference/components/pod-templates.md
  content/es/docs/using-jx/creating/create-camel.md
  content/es/docs/using-jx/creating/create-mlquickstart.md
  content/es/docs/using-jx/creating/import.md
  content/es/docs/using-jx/faq/pipelines.md
  content/zh/docs/getting-started/demos-talks-posts/create_cluster.md
  content/zh/docs/getting-started/demos-talks-posts/create_spring.md
  content/zh/docs/getting-started/first-project/create-quickstart.md
  content/zh/docs/managing-jx/common-tasks/config.md
  content/zh/docs/managing-jx/common-tasks/install-on-cluster.md
  content/zh/docs/managing-jx/common-tasks/manage-via-gitops.md
  content/zh/docs/managing-jx/common-tasks/pod-templates.md
  content/zh/docs/using-jx/common-tasks/browsing.md
  content/zh/docs/using-jx/common-tasks/create-spring.md
  docker-compose.yml
Labels: approved, size/L

#2309 docs: remove dwjw 2019 lisbon banner
  content/en/_index.html
Labels: approved, size/S

#2314 docs: brew, use one-liner where brew install does it all
  content/en/docs/getting-started/setup/install/_index.md
  content/es/docs/getting-started/setup/install/_index.md
  content/zh/docs/getting-started/setup/install/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2315 docs: brew, use one-liner where brew install does it all (2)
  content/en/_index.html
  content/es/_index.html
  content/zh/_index.html
Labels: approved, lgtm, ok-to-test, size/XS

#2322 docs: Update multi-cluster.md: add warning when using older helm version to install the environment controller
  content/en/docs/reference/multi-cluster.md
Labels: approved, lgtm, ok-to-test, size/S

#2325 docs: add post on FOSDEM schedule
  content/en/blog/news/2020-fosdem-schedule.md
Labels: approved, size/M

#2328 docs: add missing Fosdem Devroom managers
  content/en/blog/news/2020-fosdem-schedule.md
Labels: approved, lgtm, ok-to-test, size/XS

#2327 docs: edit getting started instructions
  content/en/docs/getting-started/_index.md
Labels: approved, lgtm, size/S

#2323 fix: Minimal typos and punctuation
  content/en/docs/using-jx/faq/_index.md
Labels: approved, lgtm, ok-to-test, size/S

#2320 chore: add jenkins-x-boot-config repo
  content/en/docs/reference/components/source.md
Labels: approved, lgtm, size/XS

#2333 feat: Include GKE permissions in boot storage docs
  content/en/docs/getting-started/setup/boot/_index.md
  content/en/docs/managing-jx/common-tasks/storage.md
Labels: approved, lgtm, ok-to-test, size/M

#2321 chore: remove deprecated repositories from source list
  content/en/docs/reference/components/source.md
Labels: approved, lgtm, ok-to-test, size/XS

#2332 docs: Outreachy Blog1 - 2019 - Motivation to apply
  content/en/blog/news/outreachy-blog1-2019.md
Labels: approved, lgtm, ok-to-test, size/M

#2334 docs: edits and update pipeline engine
  content/en/docs/concepts/features.md
Labels: approved, size/XS

#2341 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2342 docs: introduce Neha and her awesome Outreachy project
  content/en/blog/news/outreachy-blog1-2019.md
Labels: approved, size/XS

#2347 docs: edit typo
  content/en/blog/news/2020-fosdem-schedule.md
Labels: approved, size/XS

#2348 docs: jenkins x second birthday
  content/en/blog/news/second-birthday.md
  static/images/second-birthday/7TH_BIRTHDAY.png
  static/images/second-birthday/boxes.png
  static/images/second-birthday/cdf-logo.png
  static/images/second-birthday/cupcake.png
  static/images/second-birthday/graph.png
  static/images/second-birthday/jx-logo-stacked-color.png
  static/images/second-birthday/plane.png
  static/images/second-birthday/street.png
Labels: approved, size/L

#2349 docs: add link for steering committee
  content/en/blog/news/second-birthday.md
Labels: approved, size/XS

#2340 docs: small tweaks for install instructions
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/setup/create-cluster/google.md
Labels: approved, lgtm, size/M

#2365 fix: upgrade schedule cron should contain 5 elements
  content/en/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, size/XS

#2377 docs: update fosdem info
  content/en/community/events/_index.md
Labels: approved, size/XS

#2350 docs: add Google cluster requirements
  content/en/docs/getting-started/setup/create-cluster/google.md
Labels: approved, lgtm, ok-to-test, size/XS

#2369 docs: add new categories with jx edit storage
  content/en/docs/managing-jx/common-tasks/storage.md
  content/en/docs/reference/commands/jx_edit_storage.md
  content/en/docs/reference/commands/jx_get_storage.md
Labels: approved, lgtm, ok-to-test, size/S

#2380 docs: update office hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/XS

#2383 docs: remove cloud shell instructions
  content/en/docs/getting-started/setup/create-cluster/google.md
Labels: approved, size/S

#2373 docs: Blog 2, asking and finding help for outreachy contributions.
  content/en/blog/news/outreachy-blog2-2020.md
Labels: approved, lgtm, ok-to-test, size/M

#2385 docs: edit highlighting
  content/en/blog/news/outreachy-blog2-2020.md
Labels: approved, size/XS

#2368 docs: add jx step stash information
  content/en/docs/managing-jx/common-tasks/storage.md
  content/en/docs/reference/commands/jx_step_stash.md
Labels: approved, lgtm, ok-to-test, size/S

#2387 fix: polish the reference navigation
  README.md
  content/en/docs/getting-started/promotion/_index.md
  content/en/docs/reference/commands/_index.md
  content/en/docs/reference/commands/deprecation.md
  content/en/docs/reference/components/_index.md
  content/en/docs/reference/config/_index.md
Labels: size/M

#2388 fix: add first spike at a cloud provider section to the boot config
  content/en/docs/getting-started/setup/boot/_index.md
  content/en/docs/getting-started/setup/boot/clouds/_index.md
  content/en/docs/getting-started/setup/boot/clouds/aws.md
  content/en/docs/getting-started/setup/boot/clouds/gcp.md
  content/en/docs/getting-started/setup/boot/clouds/on-premise.md
Labels: approved, size/L

#2389 fix: simplify cloud docs
  content/en/docs/getting-started/setup/boot/clouds/_index.md
  content/en/docs/getting-started/setup/boot/clouds/amazon.md
  content/en/docs/getting-started/setup/boot/clouds/gcp.md
  content/en/docs/getting-started/setup/boot/clouds/google.md
  content/en/docs/getting-started/setup/create-cluster/google.md
Labels: size/M

#2391 docs: add community links in contributing guide
  content/en/docs/contributing/_index.md
Labels: approved, size/XS

#2395 fix: add back removed index
  content/en/docs/reference/commands/_index.md
Labels: size/XS

#2398 docs: more Jenkins X icons
  static/images/logo/jenkinsx-ico-black.png
  static/images/logo/jenkinsx-ico-black.svg
  static/images/logo/jenkinsx-ico-color.png
  static/images/logo/jenkinsx-ico-white.png
  static/images/logo/jenkinsx-ico-white.svg
  static/images/logo/jenkinsx-icon-color.svg
Labels: approved, lgtm, size/L
