Repository jenkins-x/jx-docs, pull requests merged in 2020-06, with the labels that each got.

#2828 chore: Update Prow/Lighthouse comparison
  content/en/docs/reference/components/lighthouse.md
Labels: approved, lgtm, size/S

#2834 docs: unpublishing old blog post
  content/en/blog/news/provision-jx-clusters-terraform.md
Labels: size/XS

#2836 chore: Lighthouse Goes GA blog post
  content/en/blog/news/lighthouse-goes-ga.md
Labels: approved, lgtm, size/M

#2838 refactor: remove apache camel microservice creation docs
  content/en/docs/create-project/creating/create-camel.md
Labels: approved, lgtm, size/M

#2850 chore: Update upgrade process
  content/en/docs/install-setup/upgrade-jx.md
Labels: approved, lgtm, size/M

#2857 chore: Add capabilities matrix
  content/en/about/capabilities.md
  content/en/docs/install-setup/installing/boot/clouds/_index.md
Labels: approved, lgtm, size/M

#2867 fix: add missing sections to the eks terraform docs
  content/en/docs/install-setup/installing/create-cluster/eks.md
Labels: approved, lgtm, size/M

#2868 fix: restructuring of guides and tutorials under misc resources section
  content/en/docs/resources/_index.md
  content/en/docs/resources/demos-talks-posts/_index.md
  content/en/docs/resources/faq/_index.md
  content/en/docs/resources/guides/_index.md
  content/en/docs/resources/guides/extending-jx/_index.md
  content/en/docs/resources/guides/managing-jx/_index.md
  content/en/docs/resources/guides/mlops/_index.md
  content/en/docs/resources/guides/using-jx/_index.md
  content/en/docs/resources/guides/using-jx/faq/_index.md
  content/en/docs/resources/tutorials/_index.md
  content/en/docs/resources/tutorials/custom-builder.md
  content/en/docs/resources/tutorials/google-hosted.md
  content/en/docs/resources/tutorials/image-security.md
  content/en/docs/resources/tutorials/java-gradle-app.md
  content/en/docs/resources/tutorials/progressive-delivery.md
  content/en/docs/resources/tutorials/serverless-apps.md
Labels: approved, lgtm, size/M

#2864 fix: removed duplicated "Get Started" content
  content/en/community/documentation/_index.md
  content/en/docs/_index.html
  content/en/docs/getting-started/_index.html
  content/en/docs/install-setup/_index.html
  content/en/docs/install-setup/_index.md
  content/en/docs/install-setup/configure-scm.md
  content/en/docs/install-setup/security-features.md
  content/en/docs/install-setup/upgrade-jx.md
Labels: approved, lgtm, size/XL

#2876 chore: deleting empty docs about UI
  content/en/docs/install-setup/installing/install-ui.md
Labels: approved, lgtm, size/XS

#2859 docs: Add section about using custom buildpacks
  content/en/docs/create-project/build-packs.md
Labels: approved, lgtm, size/S

#2882 refactor: replace deprecated version flag in the docs
  content/en/_index.html
  content/en/docs/_index.html
  content/en/docs/install-setup/installing/install-binary/_index.md
  content/en/docs/install-setup/upgrade-jx.md
Labels: approved, lgtm, size/S

#2886 docs: updating documentation for create cluster with GKE Terraform module
  content/en/docs/install-setup/installing/create-cluster/gke.md
Labels: approved, lgtm, size/M

#2890 fix: fix documentation contribution link in readme
  README.md
Labels: approved, lgtm, size/XS

#2879 fix: Added correct link for Vault for EKS
  content/en/docs/install-setup/installing/create-cluster/eks.md
Labels: approved, lgtm, ok-to-test, size/XS

#2901 docs: gsoc blog post
  content/en/blog/news/2020-gsoc-story-of-zixuan.md
Labels: approved, lgtm, ok-to-test, size/M

#2898 fix: updating the Docker Repository configuration
  content/en/docs/reference/components/docker-registry.md
  content/en/docs/resources/guides/managing-jx/old/_index.md
  content/en/docs/resources/guides/managing-jx/old/config.md
Labels: approved, lgtm, size/L

#2895 chore: update getting started docs to factor in terraform-google-jx changes
  content/en/docs/install-setup/installing/create-cluster/gke.md
  static/images/getting-started/terraform_google_jx_boot.png
Labels: approved, lgtm, size/S

#2918 docs: cjxd june blog post
  content/en/blog/news/cjxd-202005.md
Labels: approved, lgtm, size/M

#2905 refactor: remove minikube/minishift references
  content/en/about/_index.md
  content/en/about/concepts/_index.md
  content/en/docs/resources/demos-talks-posts/articles.md
  content/en/docs/resources/demos-talks-posts/create_cluster.md
  content/en/docs/resources/faq/issues.md
  content/en/docs/resources/guides/managing-jx/old/create-cluster.md
  content/en/docs/resources/guides/managing-jx/old/install-on-cluster-what-happens.md
  content/en/docs/resources/guides/using-jx/developing/kube-context.md
  content/es/docs/getting-started/demos-talks-posts/create_cluster.md
Labels: approved, lgtm, size/L

#2913 feat: roadmap page
  content/en/community/roadmap.md
Labels: approved, lgtm, size/M

#2909 chore: fix typo in Preview Environments documentation
  content/en/docs/build-test-preview/preview.md
Labels: approved, lgtm, ok-to-test, size/XS

#2914 fix: changing git to SCM
  content/en/docs/install-setup/installing/boot/git-provider.md
Labels: approved, lgtm, size/S

#2919 fix: deduplicating nested install structure
  content/en/docs/install-setup/boot/_index.md
  content/en/docs/install-setup/boot/clouds/_index.md
  content/en/docs/install-setup/boot/clouds/amazon.md
  content/en/docs/install-setup/boot/clouds/google.md
  content/en/docs/install-setup/boot/clouds/on-premise.md
  content/en/docs/install-setup/boot/git-provider.md
  content/en/docs/install-setup/boot/how-it-works.md
  content/en/docs/install-setup/boot/ingress.md
  content/en/docs/install-setup/boot/repository.md
  content/en/docs/install-setup/boot/secrets.md
  content/en/docs/install-setup/boot/storage.md
  content/en/docs/install-setup/boot/webhooks.md
  content/en/docs/install-setup/create-cluster/_index.md
  content/en/docs/install-setup/create-cluster/aks.md
  content/en/docs/install-setup/create-cluster/eks.md
  content/en/docs/install-setup/create-cluster/gke.md
  content/en/docs/install-setup/create-cluster/required-cloud-resources.md
  content/en/docs/install-setup/install-binary/_index.md
  content/en/docs/install-setup/installing/_index.md
  content/en/docs/install-setup/next.md
  content/en/docs/install-setup/security-features.md
  content/en/docs/install-setup/upgrade-jx.md
  content/en/docs/reference/components/docker-registry.md
  content/en/docs/reference/components/vault.md
  content/en/docs/resources/faq/boot.md
  content/en/docs/resources/guides/managing-jx/common-tasks/dns.md
  content/en/docs/resources/guides/managing-jx/common-tasks/storage.md
  content/en/docs/resources/guides/managing-jx/common-tasks/tls.md
  content/en/docs/resources/guides/using-jx/faq/_index.md
Labels: approved, lgtm, size/L

#2925 docs: updating Terraform module usage for GKE and EKS
  content/en/docs/_index.html
  content/en/docs/install-setup/create-cluster/eks.md
  content/en/docs/install-setup/create-cluster/gke.md
Labels: approved, lgtm, size/L

#2830 feat: first draft of OpenShift documentation
  content/en/docs/install-setup/installing/boot/clouds/openshift.md
Labels: approved, lgtm, size/L

#2930 docs: add links to roadmap
  content/en/community/roadmap.md
Labels: approved, lgtm, size/XS

#2940 feat: add spot instance and eks node group section
  content/en/docs/install-setup/create-cluster/eks.md
Labels: approved, lgtm, size/M

#2938 refactor: remove references to static jenkins from component section
  content/en/docs/create-project/build-packs.md
  content/en/docs/reference/components/cloud-native-jenkins.md
  content/en/docs/reference/components/decisions.md
Labels: approved, lgtm, size/M

#2942 refactor: remove feature maturity page from about section
  content/en/about/maturity.md
Labels: approved, lgtm, size/L
