Repository jenkins-x/jx-docs, pull requests merged in 2020-05, with the labels that each got.

#2715 chore: validating with google
  google834692bb5558ddf3.html
Labels: approved, lgtm, size/XS

#2723 docs: April CJXD release 9 blog post
  content/en/blog/news/cjxd-202004.md
Labels: approved, lgtm, size/M

#2724 feat: increase header height to align logos
  assets/scss/_variables_project.scss
Labels: approved, lgtm, size/XS

#2725 fix: resolve navbar options on media view
  assets/scss/_variables_project.scss
Labels: size/XS

#2722 chore: Removing google verification file
  google834692bb5558ddf3.html
Labels: approved, lgtm, size/XS

#2749 chore: fixing indentation of AWS Terraform example
  content/en/docs/getting-started/_index.html
Labels: approved, lgtm, size/S

#2717 chore: adding labs warning to all labs related documentation
  content/en/docs/labs/boot/_index.md
  content/en/docs/labs/boot/apps.md
  content/en/docs/labs/boot/background.md
  content/en/docs/labs/boot/benefits.md
  content/en/docs/labs/boot/comparison.md
  content/en/docs/labs/boot/faq/_index.md
  content/en/docs/labs/boot/getting-started/_index.md
  content/en/docs/labs/boot/getting-started/cloud/_index.md
  content/en/docs/labs/boot/getting-started/cloud/gcloud.md
  content/en/docs/labs/boot/getting-started/cloud/terraform.md
  content/en/docs/labs/boot/getting-started/config.md
  content/en/docs/labs/boot/getting-started/repository.md
  content/en/docs/labs/boot/getting-started/run.md
  content/en/docs/labs/boot/getting-started/secrets/_index.md
  content/en/docs/labs/boot/getting-started/secrets/vault.md
  content/en/docs/labs/boot/how-it-works.md
  content/en/docs/labs/boot/multi-cluster.md
  content/en/docs/labs/boot/progressive-delivery.md
  content/en/docs/labs/jenkins/_index.md
  content/en/docs/labs/jenkins/getting-started.md
  content/en/docs/labs/jenkins/importing.md
  content/en/docs/labs/jenkins/overview.md
  content/en/docs/labs/jxl.md
  content/en/docs/labs/wizard/_index.md
  content/en/docs/labs/wizard/jenkins.md
  content/en/docs/labs/wizard/overview.md
Labels: approved, lgtm, size/L

#2733 chore: move contrib to top nav
  content/en/blog/news/2020-season-of-docs.md
  content/en/blog/news/hacktoberfest-2019.md
  content/en/blog/news/jenkins-x-joins-cdf.md
  content/en/community/_index.md
  content/en/community/addons/_index.md
  content/en/community/addons/plugins.md
  content/en/community/addons/worked-example.md
  content/en/community/code/_index.md
  content/en/community/code/builder-images.md
  content/en/community/code/continuous-integrating-jx-itself.md
  content/en/community/code/contribute_dns.md
  content/en/community/code/pullrequestreview.md
  content/en/community/code/triage.md
  content/en/community/documentation/_index.md
  content/en/community/documentation/apidocs.md
  content/en/community/documentation/changes.md
  content/en/community/documentation/reference.md
  content/en/community/documentation/step-by-step.md
  content/en/community/documentation/workflow.md
  content/en/community/events/_index.md
  content/en/community/events/talksdemos/past-talks-and-demos.md
  content/en/community/newsletter/_index.md
  content/en/community/office_hours/_index.md
  content/en/community/security.md
  content/en/community/sponsors.md
  content/en/docs/contributing/_index.md
  content/es/docs/contributing/_index.md
  content/es/docs/contributing/documentation/_index.md
  content/zh/docs/contributing/code/_index.md
  content/zh/docs/contributing/documentation/_index.md
  layouts/404.html
  layouts/partials/navbar-community-selector.html
  layouts/partials/navbar.html
Labels: approved, lgtm, size/L

#2761 fix: Updating boot redirect
  content/en/about/_index.md
  content/zh/docs/getting-started/setup/boot/_index.md
Labels: approved, lgtm, size/M

#2764 fix: making sure base URL for the release site is set to https://jenkins-x.io
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#2772 docs: update hours
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, lgtm, size/XS

#2773 docs: add calendar
  content/en/community/_index.md
Labels: approved, lgtm, size/XS

#2774 docs: rearrange community page
  content/en/community/_index.md
Labels: approved, lgtm, size/M

#2775 docs: add calendar to other community pages
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, lgtm, size/M

#2780 docs: clean up community pages
  content/en/community/sponsors.md
Labels: approved, lgtm, size/S

#2776 docs: create event calendar page
  content/en/community/calendar.md
Labels: approved, lgtm, size/S

#2783 fix: Softening monorepo language
  content/en/docs/guides/using-jx/faq/_index.md
Labels: approved, lgtm, size/S

#2785 docs: add events section to landing page; remove events directory
  content/en/community/README.md
  content/en/community/_index.md
  content/en/community/events/_index.md
  content/en/community/events/talksdemos/past-talks-and-demos.md
Labels: approved, lgtm, size/L

#2788 chore: add list of contributors to community page
  content/en/community/_index.md
  layouts/shortcodes/calendar.html
  layouts/shortcodes/contributors.html
  layouts/shortcodes/mailchimp.html
Labels: approved, lgtm, size/L

#2789 docs: jxl and helm 3 blog post
  content/en/blog/news/may-2020-jxl-helm3-update.md
Labels: size/M

#2791 fix: Parsing yaml file
  docker-compose.yml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2798 docs: add to GSoD project ideas list
  content/en/blog/news/2020-season-of-docs.md
Labels: approved, lgtm, size/XS

#2794 fix: Typo in community documentation
  content/en/community/documentation/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2805 fix: code snippet for main.tf
  content/en/docs/getting-started/_index.html
Labels: approved, lgtm, size/XS

#2782 docs: Add a notice/doc to warn about not puting a config.json at the root folder
  content/en/docs/guides/using-jx/creating/import.md
Labels: approved, lgtm, ok-to-test, size/XS

#2811 chore: refine grammar for link to installation instructions
  content/en/docs/getting-started/_index.html
Labels: approved, lgtm, size/XS

#2814 fix: bump version of go in the contribution guide
  content/en/community/code/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#2768 docs: add eks ingress section to faqs
  content/en/docs/resources/faq/issues.md
Labels: approved, lgtm, size/S

#2816 fix: Update reate-custom-builder.md and move it to the deprecated section
  content/en/docs/resources/guides/managing-jx/old/create-custom-builder.md
Labels: approved, lgtm, size/S

#2819 docs: remove reference to jxl experimental info
  content/en/docs/reference/multi-cluster.md
Labels: size/S

#2810 docs: unpublishing this page, as it refers to labs
  content/en/docs/reference/multi-cluster.md
Labels: size/S

#2818 fix: restoring /docs redirect
  content/en/docs/getting-started/_index.html
Labels: approved, lgtm, size/XS
