Repository jenkins-x/jx-docs, pull requests merged in 2021-06, with the labels that each got.

#3353 docs: Added MLOps docs for v3
  content/en/v3/mlops/_index.md
  content/en/v3/mlops/data.md
  content/en/v3/mlops/gpu.md
  content/en/v3/mlops/introduction.md
  content/en/v3/mlops/mlquickstarting.md
  content/en/v3/mlops/mlquickstarts.md
Labels: size/XL

#3350 Update changes.md
  content/en/v3/about/changes.md
Labels: needs-ok-to-test, size/XS

#3349 Update multi-cluster.md
  content/en/v3/admin/guides/multi-cluster/multi-cluster.md
Labels: needs-ok-to-test, size/XS

#3355 fix: add v2 warning
  layouts/partials/breadcrumb.html
Labels: size/S

#3358 fix: add better demos for previews
  content/en/v3/develop/developing/_index.md
  content/en/v3/develop/environments/preview.md
  layouts/partials/breadcrumb.html
Labels: approved, size/S

#3362 chore: add docs for domain per env with tls
  content/en/v3/admin/setup/ingress/tls_dns/tls.md
Labels: approved, lgtm, ok-to-test, size/M

#3368 fix: add FAQ on annotating namespaces
  content/en/v3/develop/faq/config/charts.md
Labels: approved, size/XS

#3361 chore: Link to https
  content/en/community/_index.md
Labels: needs-ok-to-test, size/XS

#3365 chore: corrected typo on index.md
  content/en/v3/about/overview/_index.md
Labels: needs-ok-to-test, size/XS

#3367 Update azure.md
  content/en/v3/admin/setup/ingress/tls_dns/azure.md
Labels: approved, ok-to-test, size/XS

#3378 fix: add lighthouse web UI docs
  content/en/v3/develop/ui/dashboard.md
Labels: approved, size/S

#3377 fix: ensure the osiris helmfile is valid
  content/en/v3/admin/guides/preview-environments/_index.md
Labels: needs-ok-to-test, size/XS

#3376 docs: add lighthouse webui plugin
  content/en/v3/admin/guides/lighthouse-webui/_index.md
  content/en/v3/develop/ui/lighthouse.md
  static/images/lighthouse-webui-plugin/events.png
  static/images/lighthouse-webui-plugin/github-pr-status-link.png
  static/images/lighthouse-webui-plugin/jobs.png
  static/images/lighthouse-webui-plugin/merge-history.png
  static/images/lighthouse-webui-plugin/merge-status.png
Labels: approved, lgtm, ok-to-test, size/L

#3379 fix: typo in the lighthouse webui install guide
  content/en/v3/admin/guides/lighthouse-webui/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#3380 fix: add changes about Ingress v1
  content/en/v3/about/changes.md
Labels: approved, size/XS

#3383 chore: add note on using up to date cluster
  content/en/blog/news/2021-databases.md
Labels: approved, size/XS

#3384 fix: add azure service operator link
  content/en/blog/news/2021-databases.md
Labels: approved, size/XS

#3381 fix: [Docs/Bug] Mobile view updated
  static/css/style.css
Labels: ok-to-test, size/XS

#3388 docs: blog on using argo cd with Jenkins X
  content/en/blog/news/2021-argo.md
  static/images/v3/argocd.png
Labels: approved, size/L

#3390 fix: reuse the updatebot task
  content/en/blog/news/2021-argo.md
Labels: approved, lgtm, size/XS

#3389 docs: Fix typo in title of Troubleshooting page
  content/en/v3/develop/faq/issues.md
Labels: needs-ok-to-test, size/XS

#3391 fix: better docs on setting up ngrok
  content/en/v3/admin/platforms/on-premises/webhooks.md
Labels: approved, size/M
