Repository jenkins-x/jx-docs, pull requests merged in 2021-01, with the labels that each got.

#3196 chore: add a note on ecr repo creation before running quickstart or i…
  content/en/v3/admin/platforms/eks.md
Labels: size/XS

#3197 fix: add docs on developing plugins
  content/en/v3/about/extending.md
Labels: approved, size/M

#3198 fix: add docs on environments and promotion
  content/en/v3/develop/environments/_index.md
  content/en/v3/develop/environments/config.md
  content/en/v3/develop/environments/git.md
  content/en/v3/develop/environments/promotion.md
Labels: approved, size/L

#3201 fix: added alias
  content/en/v3/admin/platforms/openshift/_index.md
Labels: size/XS

#3202 fix: add alias
  content/en/v3/admin/platforms/openshift/_index.md
Labels: approved, size/XS

#3204 fix: add blog post for jx-pipelines-visualizer v1
  content/en/blog/news/2021-pipelines-visualizer-v1.md
  static/images/jx-pipelines-visualizer/v1-home.png
  static/images/jx-pipelines-visualizer/v1-pipeline-success-with-timeline.png
  static/images/jx-pipelines-visualizer/v1-pipeline-success.png
Labels: approved

#3203 chore: fix docs for alpha -> beta
  content/en/v3/about/maturity-matrix.md
  content/en/v3/about/overview/_index.md
  content/en/v3/admin/guides/jx3.md
Labels: size/S

#3205 chore: tidy up tls docs
  content/en/v3/admin/guides/tls_dns.md
Labels: approved, size/S

#3206 feat(doc): add TLS and DNS for Azure
  content/en/v3/admin/guides/tls_dns.md
  static/images/v3/registrar_dns_servers.png
  static/images/v3/registrar_dns_servers_update.png
Labels: approved, lgtm, ok-to-test, size/L

#3207 docs: add cluster recovery docs for GCP
  content/en/v3/admin/guides/cluster-recovery.md
  static/images/v3/gcp_delete_recordsets.png
  static/images/v3/gcp_delete_zone.png
  static/images/v3/gcp_select_zone.png
Labels: approved, size/L

#3210 docs: v3 walkthrough blog
  content/en/blog/news/2021-jx3-walkthroughs.md
Labels: approved, size/L

#3192 chore: update link for kubernetes-external-secrets
  content/en/v3/about/overview/_index.md
Labels: needs-ok-to-test, size/XS

#3209 docs: Add Chinese document of create project
  content/zh/v3/develop/create-project/_index.md
Labels: approved, size/M

#3213 fix: added a couple more videos
  content/en/v3/admin/guides/cluster-recovery.md
  content/en/v3/admin/guides/tls_dns.md
  content/en/v3/develop/pipeline-catalog.md
Labels: approved, size/S

#3216 fix: add better pipeline docs
  content/en/v3/about/changes.md
  content/en/v3/about/extending.md
  content/en/v3/about/how-it-works.md
  content/en/v3/about/overview/projects.md
  content/en/v3/admin/guides/migrate/v3-alpha.md
  content/en/v3/develop/environments/promotion.md
  content/en/v3/develop/faq/_index.md
  content/en/v3/develop/pipeline-catalog.md
  content/en/v3/develop/pipelines/_index.md
  content/en/v3/develop/pipelines/catalog.md
  content/en/v3/develop/pipelines/demo.md
  content/en/v3/develop/pipelines/editing.md
  content/en/v3/develop/pipelines/reference.md
  content/en/v3/develop/pipelines/upgrading.md
Labels: size/XL

#3219 fix: add docs on converting pipelines
  content/en/v3/admin/guides/migrate/v2.md
  content/en/v3/admin/guides/migrate/v3-alpha.md
  content/en/v3/develop/pipelines/upgrading.md
Labels: size/S
