Repository jenkins-x/jx-docs, pull requests merged in 2021-03, with the labels that each got.

#3253 fix: add vault FAQ
  content/en/v3/develop/faq/config/vault.md
Labels: approved, size/S

#3254 fix: upgrade hugo
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#3255 fix: added better preview environment guide
  content/en/docs/build-test-preview/preview.md
  content/en/v3/about/changes.md
  content/en/v3/develop/environments/preview.md
Labels: approved, size/L

#3256 fix: add FAQ on migrating to GSM
  content/en/v3/develop/faq/config/secrets.md
Labels: approved, size/M

#3257 fix: add new FAQs
  content/en/v3/develop/faq/issues.md
  content/en/v3/develop/faq/pipeline.md
Labels: size/M

#3260 fix: add FAQ on removing applications
  content/en/v3/develop/faq/using.md
Labels: approved, size/S

#3261 fix: typo and add details on the SourceRepository
  content/en/v3/develop/faq/using.md
Labels: approved, size/S

#3258 docs: Typo corrections
  content/en/v3/admin/guides/jenkins/example.md
Labels: needs-ok-to-test, size/XS

#3259 fix: Install operator: remove delete_repo permission
  content/en/v3/admin/setup/operator/_index.md
Labels: needs-ok-to-test, size/XS

#3262 chore: typo
  content/en/v3/develop/faq/using.md
Labels: size/XS

#3263 chore: fix capitalisation
  content/en/v3/develop/faq/using.md
Labels: size/XS

#3264 docs: Add cluster rebuild example
  content/en/v3/admin/guides/cluster-recovery/_index.md
  content/en/v3/admin/guides/cluster-recovery/cluster-demo.md
  content/en/v3/admin/guides/cluster-recovery/cluster-rebuild.md
Labels: approved, ok-to-test, size/L

#3265 docs: multi-cluster example
  content/en/v3/admin/guides/multi-cluster/_index.md
  content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md
  content/en/v3/admin/guides/multi-cluster/multi-cluster.md
  static/images/v3/setContainer.png
Labels: approved, lgtm, ok-to-test, size/L

#3268 fix: add inner loop docs
  content/en/v3/develop/faq/using.md
  content/en/v3/develop/pipelines/inner-loop/_index.md
  content/en/v3/develop/pipelines/inner-loop/ksync.md
  content/en/v3/develop/pipelines/inner-loop/okteto.md
  content/en/v3/develop/pipelines/inner-loop/skaffold.md
Labels: approved, size/M

#3267 fix: complete bucketrepo
  content/en/v3/admin/setup/config/repository.md
Labels: approved, ok-to-test, size/S

#3269 fix: add article and localizer docs
  content/en/v3/develop/pipelines/inner-loop/_index.md
  content/en/v3/develop/pipelines/inner-loop/localizer.md
Labels: approved, size/M

#3272 docs: add FAQ on renew tekton certs
  content/en/v3/develop/faq/issues.md
Labels: approved, size/XS

#3273 fix: add notes on avoiding nginx
  content/en/v3/admin/platforms/on-premise/_index.md
Labels: approved, size/XS

#3274 fix: add a FAQ on using private repos
  content/en/v3/develop/faq/config/charts.md
Labels: approved, size/M

#3275 feat: add an observability admin guide
  content/en/v3/admin/guides/observability/_index.md
Labels: approved, lgtm, ok-to-test, size/L

#3271 docs: enhance multi-cluster-example.md
  content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md
Labels: approved, lgtm, ok-to-test, size/L

#3277 fix: first spike of a CD pattern catalog
  content/en/v3/develop/environments/config.md
  content/en/v3/devops/patterns/_index.md
  content/en/v3/devops/patterns/automate_continuous_delivery.md
  content/en/v3/devops/patterns/gitops.md
  content/en/v3/devops/patterns/pipeline_as_code.md
  content/en/v3/devops/patterns/prefer_cloud_over_kube.md
  content/en/v3/devops/patterns/preview_environments.md
  content/en/v3/devops/patterns/pull_dependent_versions.md
  content/en/v3/devops/patterns/push_version_changes.md
  content/en/v3/devops/patterns/trunk_based_development.md
  content/en/v3/devops/patterns/version_everything.md
Labels: approved, lgtm, size/L

#3280 chore: add an admin guide to install osiris for preview envs
  content/en/v3/admin/guides/observability/_index.md
  content/en/v3/admin/guides/preview-environments/_index.md
  content/en/v3/develop/environments/preview.md
Labels: approved, lgtm, ok-to-test, size/M

#3278 docs: lets tidy up the what is Jenkins X from a renewed view of v3
  content/en/v3/about/comparison.md
  content/en/v3/about/overview/_index.md
  content/en/v3/about/what.md
  content/en/v3/develop/environments/promotion.md
Labels: approved, size/M
