Repository jenkins-x/jx-docs, pull requests merged in 2021-08, with the labels that each got.

#3411 fix: added docs about Lens
  config.toml
  content/en/v3/develop/environments/preview.md
  content/en/v3/develop/ui/dashboard.md
  content/en/v3/develop/ui/lens.md
  content/en/v3/develop/ui/lighthouse.md
  content/en/v3/develop/ui/octant.md
  layouts/shortcodes/jx-lens-version.html
Labels: approved, size/M

#3409 Fixed typos
  content/en/v3/develop/environments/promotion/_index.md
Labels: size/XS, needs-ok-to-test

#3413 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.12
  config.toml
Labels: size/XS, updatebot

#3414 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.13
  config.toml
Labels: size/XS, updatebot

#3415 fix: add Lens screenshot
  content/en/v3/develop/ui/lens.md
  static/images/lens/lens.png
Labels: approved, size/XS

#3416 fix: add PR comment variables docs
  content/en/v3/develop/reference/variables.md
Labels: approved, size/M

#3417 fix: add FAQ on upgrade cli
  content/en/v3/develop/faq/issues.md
Labels: size/S

#3418 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.14
  config.toml
Labels: size/XS, updatebot

#3419 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.15
  config.toml
Labels: size/XS, updatebot

#3422 fix: add docs for custom git repositories
  content/en/v3/admin/setup/config/repository.md
  content/en/v3/develop/pipelines/catalog.md
  content/en/v3/develop/ui/lens.md
Labels: approved, size/M

#3420 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.16
  config.toml
Labels: size/XS, updatebot

#3423 fix: add blog on gitops and secrets
  content/en/blog/news/2021-gitops-secrets.md
  content/en/v3/admin/setup/config/repository.md
Labels: approved, size/L

#3424 fix: add blog on debugging pipelines
  content/en/blog/news/2021-debug-tekton.md
  content/en/blog/news/2021-gitops-secrets.md
  content/en/v3/develop/faq/previews.md
  content/en/v3/develop/pipelines/debugging.md
Labels: approved, size/L
