Repository jenkins-x/jx-docs, pull requests merged in 2021-12, with the labels that each got.

#3490 fix: small note on deprecated plugins
  content/en/v3/admin/setup/upgrades/cli.md
Labels: approved, size/XS

#3491 refactor: add a note about manually deleting webhooks from repositories
  content/en/v3/admin/uninstall/_index.md
  content/en/v3/admin/uninstall/delete-jx-cluster.md
  content/en/v3/admin/uninstall/delete-jx.md
Labels: approved, size/XS

#3492 fix: update docs now that external vault support is stable
  content/en/v3/admin/platforms/eks/_index.md
  content/en/v3/admin/setup/secrets/vault.md
Labels: approved, size/M, lgtm

#3493 refactor: add more information about boot secrets
  content/en/v3/admin/setup/secrets/vault.md
Labels: approved, size/XS

#3495 refactor: add more information around error messages for k3s install …
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/M

#3496 fix: add some troubleshooting information around installation
  content/en/v3/admin/troubleshooting/bot-token.md
  content/en/v3/admin/troubleshooting/install.md
  content/en/v3/admin/troubleshooting/secrets.md
  content/en/v3/admin/troubleshooting/webhooks.md
Labels: approved, size/M

#3497 fix: add a note on gitlab nested repositories
  content/en/v3/develop/create-project/_index.md
Labels: approved, size/M

#3498 fix: add a note about installing vault cli
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/XS

#3500 chore: added new blog post for issues with azure
  content/en/blog/news/2021-kaniko-azure-resolution.md
  content/en/v3/admin/platforms/azure/_index.md
Labels: approved, size/L, lgtm, ok-to-test

#3501 fix: add a note about jq installation and k8s 1.22 support
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/XS

#3502 feat: add troubleshooting guide around import and quickstart
  content/en/v3/admin/troubleshooting/install.md
  content/en/v3/admin/troubleshooting/quickstart-import.md
Labels: approved, size/L
