Repository jenkins-x/jx-docs, pull requests merged in 2021-07, with the labels that each got.

#3392 fix: broken link
  content/en/v3/develop/ui/cli.md
Labels: approved, lgtm, ok-to-test, size/XS

#3394 fix: add upgrade job workaround
  content/en/v3/about/changes.md
Labels: approved, size/S

#3395 fix: add note on port forward for vault
  content/en/v3/develop/ui/slack.md
Labels: approved, size/XS

#3396 fix: remove old import/export command docs
  content/en/v3/admin/setup/secrets/_index.md
Labels: approved, size/M

#3397 fix: add better instructions for how to install jx
  config.toml
  content/en/v3/admin/setup/jx3/_index.md
  layouts/shortcodes/version.html
Labels: approved

#3398 fix: use correct time for office hours
  content/en/community/_index.md
Labels: approved, size/XS

#3401 chore: add docs for updatebot with custom pipeline catalogs
  content/en/v3/about/extending.md
Labels: approved, lgtm, ok-to-test, size/M

#3399 docs: add instructions to generate random secret-cookie
  content/en/v3/admin/setup/ingress/oauth/_index.md
  static/images/v3/oauth_secret_edit.png
Labels: approved, lgtm, ok-to-test, size/S

#3402 fix: add a couple more FAQs
  content/en/v3/develop/faq/chatops.md
  content/en/v3/develop/faq/previews.md
Labels: approved, size/M

#3403 fix: add a couple more FAQs
  content/en/v3/develop/faq/config/secrets.md
Labels: approved, size/M

#3405 fix: avoid JavaScript loading errors
  layouts/partials/scripts.html
Labels: approved, size/XS

#3406 fix: polish home page
  content/en/_index.html
Labels: approved, size/S

#3407 fix: polish FAQ
  content/en/_index.html
  content/en/v3/develop/faq/using.md
Labels: approved, size/S

#3408 fix: add FAQ on creating preview secrets
  content/en/v3/about/how-it-works.md
  content/en/v3/develop/faq/previews.md
Labels: approved, size/M
