Repository jenkins-x/jx-docs, pull requests merged in 2021-11, with the labels that each got.

#3478 fix: improved chartmuseum 500 error FAQ
  content/en/v3/develop/faq/issues.md
Labels: approved, lgtm, size/S, ok-to-test

#3477 fix: clarify commit types and scopes (#3474)
  content/en/community/code/_index.md
Labels: approved, lgtm, size/S, ok-to-test

#3480 fix: add links to jx3-eks-asm template
  content/en/v3/admin/platforms/eks/_index.md
  content/en/v3/develop/ui/slack.md
Labels: approved, size/L, lgtm

#3481 fix: use shallow clone for submodules
  .gitmodules
Labels: approved, size/XS, lgtm, ok-to-test

#3482 fix (external-vault): instructions how-to proxy jx-secret to external vault
  content/en/v3/admin/setup/secrets/vault.md
Labels: approved, size/M, lgtm, ok-to-test

#3484 refactor: blog on hacktoberfest 2021 conclusion
  content/en/blog/news/2021-hacktoberfest-conclusion.md
Labels: approved, size/M

#3486 refactor: clear instructions on how to uninstall jx
  content/en/v3/admin/guides/_index.md
  content/en/v3/admin/setup/_index.md
  content/en/v3/admin/troubleshooting/_index.md
  content/en/v3/admin/uninstall/_index.md
  content/en/v3/admin/uninstall/delete-jx-cluster.md
  content/en/v3/admin/uninstall/delete-jx.md
Labels: approved, size/M, lgtm

#3487 feat: add a platform section for k3s
  content/en/v3/admin/platforms/k3s/_index.md
  content/en/v3/admin/platforms/minikube/_index.md
  content/en/v3/admin/platforms/on-premises/_index.md
  layouts/shortcodes/admincards.html
  static/images/logo/k3s-horizontal-color.svg
Labels: approved, size/L, lgtm

#3489 fix: Typo in help command
  content/en/v3/admin/setup/jx3/_index.md
Labels: approved, size/XS, lgtm, ok-to-test
