Repository jenkins-x/jx-docs, pull requests merged in 2021-02, with the labels that each got.

#3220 docs: feb 21 lts
  content/en/blog/news/2021-jx3-feb-lts.md
Labels: approved, size/M

#3221 chore: tidy grammer
  content/en/blog/news/2021-jx3-feb-lts.md
Labels: approved, size/XS

#3222 fix: add note on new tekton and pipeline convert
  content/en/v3/about/changes.md
Labels: approved, size/XS

#3223 fix(doc): link the custom pipeline catalog page as it's in a completl…
  content/en/v3/develop/pipelines/catalog.md
Labels: needs-ok-to-test, size/XS

#3227 docs: added migrations.md to detail occasional manual migrations required on upgrade
  content/en/v3/admin/guides/upgrades/migrations.md
Labels: ok-to-test, size/M

#3228 fix: add better FAQ entry
  content/en/v3/admin/troubleshooting/webhooks.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/S

#3229 fix: first spike of a devops docs section
  content/en/docs/resources/faq/using/_index.md
  content/en/v3/about/benefits.md
  content/en/v3/about/overview/projects.md
  content/en/v3/admin/guides/jenkins/gitops.md
  content/en/v3/admin/guides/secrets/_index.md
  content/en/v3/admin/guides/secrets/vault.md
  content/en/v3/develop/faq/_index.md
  content/en/v3/devops/_index.md
  content/en/v3/devops/accelerate.md
  content/en/v3/devops/cloud-native.md
  content/en/v3/devops/gitops.md
Labels: size/L

#3230 fix: add a note on IAM roles
  content/en/v3/devops/cloud-native.md
  content/en/v3/devops/gitops.md
Labels: approved, size/S

#3231 fix: polish FAQ
  content/en/v3/about/changes.md
  content/en/v3/develop/faq/_index.md
Labels: approved, size/XS

#3232 docs: polish FAQ
  content/en/v3/develop/faq/_index.md
Labels: approved, size/XS

#3235 fix: add file reference sectioni and slack docs
  content/en/v3/about/changes.md
  content/en/v3/admin/guides/cluster-recovery/_index.md
  content/en/v3/admin/guides/config/_index.md
  content/en/v3/admin/guides/health/_index.md
  content/en/v3/admin/guides/jx3/_index.md
  content/en/v3/admin/guides/multi-cluster/_index.md
  content/en/v3/admin/guides/operator/_index.md
  content/en/v3/admin/guides/progressive-delivery/_index.md
  content/en/v3/admin/guides/tls_dns/_index.md
  content/en/v3/admin/platforms/azure/_index.md
  content/en/v3/admin/platforms/eks/_index.md
  content/en/v3/admin/platforms/on-premise/_index.md
  content/en/v3/develop/apps/_index.md
  content/en/v3/develop/reference/_index.md
  content/en/v3/develop/reference/files.md
  content/en/v3/develop/reference/pipelines.md
  content/en/v3/develop/ui/slack.md
  static/images/slack/slack-oauth-page.png
Labels: approved, size/L

#3236 fix: use compact menu by default
  config.toml
Labels: size/XS

#3237 chore: lets split the pipeline and variables pages
  content/en/v3/develop/reference/pipelines.md
  content/en/v3/develop/reference/variables.md
  content/en/v3/develop/ui/slack.md
Labels: approved, size/L

#3239 fix: add dockerfile and owners files
  content/en/v3/admin/troubleshooting/_index.md
  content/en/v3/develop/reference/files.md
  content/en/v3/devops/_index.md
Labels: approved, size/S

#3240 fix: add in Herve's additions
  content/en/v3/develop/reference/files.md
Labels: size/XS

#3241 fix: jenkins docs
  content/en/v3/admin/guides/jenkins/example.md
  static/images/v3/octant_display.png
Labels: approved, lgtm, ok-to-test, size/L

#3242 fix: add example of slack
  content/en/v3/develop/reference/files.md
  content/en/v3/develop/ui/slack.md
  static/images/slack/slack-bot.png
Labels: approved, size/S

#3246 fix: polish FAQ
  content/en/v3/develop/faq/_index.md
  content/en/v3/develop/faq/config/general.md
  content/en/v3/develop/faq/config/secrets.md
  content/en/v3/develop/faq/using.md
  content/en/v3/develop/reference/files.md
Labels: approved, size/L

#3249 fix: update the configuration section
  content/en/v3/admin/setup/config/_index.md
  content/en/v3/admin/setup/config/git.md
  content/en/v3/admin/setup/config/ingress.md
  content/en/v3/admin/setup/config/repository.md
  content/en/v3/admin/setup/config/storage.md
  content/en/v3/develop/faq/config/general.md
  content/en/v3/develop/faq/issues.md
Labels: approved, size/XL

#3243 cdCon cfp blog post proposal
  content/en/blog/news/2021-cdcon-cfp.md
  static/images/cdcon-cfp-jx.png
Labels: approved, ok-to-test, size/M

#3250 fix: lets move the ingress/tls docs together
  content/en/v3/admin/guides/tls_dns/_index.md
  content/en/v3/admin/setup/ingress/_index.md
  content/en/v3/admin/setup/ingress/default.md
  content/en/v3/admin/setup/ingress/tls_dns/_index.md
  content/en/v3/admin/setup/ingress/tls_dns/azure.md
  content/en/v3/admin/setup/ingress/tls_dns/background.md
  content/en/v3/admin/setup/ingress/tls_dns/cluster.md
  content/en/v3/admin/setup/ingress/tls_dns/demo.md
  content/en/v3/admin/setup/ingress/tls_dns/faq.md
  content/en/v3/admin/setup/ingress/tls_dns/google.md
  content/en/v3/admin/setup/secrets/_index.md
Labels: size/XL

#3252 fix: improve the docs around finding apps
  content/en/v3/admin/setup/secrets/_index.md
  content/en/v3/develop/apps/_index.md
  content/en/v3/develop/faq/using.md
  content/en/v3/develop/reference/files.md
Labels: approved, size/M
