Repository jenkins-x/jx-docs, pull requests merged in 2021-10, with the labels that each got.

#3453 docs: add virtualbox prerequisite
  content/en/v3/admin/platforms/minikube/_index.md
Labels: approved, size/XS, ok-to-test

#3438 docs: typo to "mutating" fixed in docs
  content/en/blog/news/2021-moving-v2-infra.md
Labels: size/XS, needs-ok-to-test

#3458 fix: minor spelling error fixed
  content/en/v3/about/changes.md
Labels: approved, size/XS, ok-to-test

#3459 feat: add documentation around external vault
  content/en/v3/admin/platforms/eks/_index.md
  content/en/v3/admin/setup/secrets/vault.md
Labels: approved, size/M, lgtm

#3460 feat: add a short blog on hacktoberfest 2021
  content/en/blog/news/2021-hacktoberfest.md
Labels: approved, size/M

#3475 fix: remove references to Discourse (fixes #3473)
  content/en/community/_index.md
  content/zh/docs/contributing/code/_index.md
Labels: approved, size/XS, lgtm, ok-to-test
