Repository jenkins-x/jx-docs, pull requests merged in 2021-09, with the labels that each got.

#3430 docs: add extra details for migrating v2 installs to GH
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3433 chore: upadte more v2 docs when migrating to github
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3435 fixed the docker image tag.
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/XS, lgtm, ok-to-test

#3436 chore: use correct command
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/XS

#3437 Expand override needed to replace gcr.io images with ghcr.io ones
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M, lgtm, ok-to-test

#3439 chore: more v2 GitHub migration edge case steps
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3440 chore: migration docs update patch version to use as there was an inc…
  .lighthouse/jenkins-x/release.yaml
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3442 chore: use correct tag
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3444 fix: v3 admin guide for lighthouse-webui
  content/en/v3/admin/guides/lighthouse-webui/_index.md
Labels: approved, size/XS, ok-to-test

#3446 fix: update list for builder image on app repos
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  content/en/blog/news/2021-moving-v2-infra.md
Labels: approved, size/M

#3449 chore: start troubleshooting guides for tokens, secrets and install t…
  .lighthouse/jenkins-x/preview.yaml
  charts/preview/values.yaml
  content/en/v3/admin/troubleshooting/bot-token.md
  content/en/v3/admin/troubleshooting/install.md
  content/en/v3/admin/troubleshooting/secrets.md
Labels: approved, size/M

#3451 chore: updating multi-cluster-example chart paths
  content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md
Labels: approved, size/M, lgtm, ok-to-test

#3452 fix: Update what.md
  content/en/v3/about/what.md
Labels: approved, size/XS, lgtm, ok-to-test
