Repository jenkins-x/jx-docs, pull requests merged in 2021-04, with the labels that each got.

#3282 feat: add Continuous Delivery Indicators docs
  content/en/v3/admin/guides/observability/_index.md
  content/en/v3/admin/guides/observability/cd-indicators.md
  content/en/v3/admin/guides/observability/platform-observability.md
  static/images/v3/observability_cd_indicators_repository.png
  static/images/v3/observability_platform_cert-manager.png
Labels: approved, lgtm, ok-to-test, size/L

#3285 fix: add docs on automatic upgrades
  .gitignore
  content/en/v3/admin/setup/upgrades/cluster.md
  content/en/v3/develop/faq/pipeline.md
  content/en/v3/develop/reference/jx/_index.md
Labels: approved, size/M

#3284 docs: new blog post for the built-in observability
  content/en/blog/news/2021-jx3-builtin-observability.md
Labels: approved, lgtm, ok-to-test, size/M

#3283 docs: new blog post for scaling preview envs with osiris
  content/en/blog/news/2021-jx3-osiris-preview-envs.md
  content/en/v3/admin/guides/preview-environments/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#3286 fix: added auto merge docs
  content/en/v3/admin/setup/upgrades/cluster.md
Labels: approved, size/XS

#3289 fix: add jx CLI links
  content/en/v3/about/changes.md
  content/en/v3/about/extending.md
  content/en/v3/about/overview/source.md
  content/en/v3/admin/setup/jx3/_index.md
  content/en/v3/admin/setup/upgrades/cli.md
  content/en/v3/develop/reference/jx-help.md
  content/en/v3/develop/reference/jx/_index.md
  content/en/v3/develop/reference/variables.md
  content/en/v3/develop/ui/cli.md
Labels: approved, size/M

#3291 chore: fix old jx-cli links
  content/en/_index.html
  content/en/docs/reference/components/source.md
  content/en/v3/about/changes.md
  content/en/v3/about/extending.md
  content/en/v3/admin/setup/upgrades/cli.md
  content/en/v3/devops/patterns/push_version_changes.md
Labels: approved, size/S

#3292 docs: add doc for grafana tempo
  content/en/v3/admin/guides/observability/platform-observability.md
Labels: approved, lgtm, ok-to-test, size/XS

#3293 docs: add more links to the CLI reference
  content/en/v3/about/changes.md
  content/en/v3/about/how-it-works.md
  content/en/v3/admin/guides/migrate/v2.md
  content/en/v3/admin/guides/migrate/v3-alpha.md
  content/en/v3/admin/guides/multi-cluster/multi-cluster.md
  content/en/v3/admin/setup/upgrades/cluster.md
  content/en/v3/develop/create-project/_index.md
  content/en/v3/develop/create-project/jenkinsfile.md
  content/en/v3/develop/environments/config.md
  content/en/v3/develop/environments/preview.md
  content/en/v3/develop/faq/general.md
  content/en/v3/develop/faq/pipeline.md
  content/en/v3/develop/pipelines/catalog.md
  content/en/v3/develop/pipelines/editing.md
  content/en/v3/develop/pipelines/upgrading.md
Labels: approved, size/M

#3294 docs: new blog post for pipeline trace
  content/en/blog/news/2021-jx3-pipeline-trace.md
  static/images/jx-pipelines-visualizer/pipeline-trace.gif
  static/images/v3/observability_pipeline_trace.png
Labels: approved, lgtm, ok-to-test, size/M

#3296 fix: add a developing guide and ChatOps reference
  content/en/v3/develop/developing/_index.md
  content/en/v3/develop/reference/chatops.md
Labels: approved, size/M

#3297 fix: polish the developing page a bit more
  content/en/v3/develop/developing/_index.md
Labels: approved, size/S

#3295 docs: update jx-pipelines-visualizer doc
  content/en/v3/develop/ui/dashboard.md
Labels: approved, lgtm, ok-to-test, size/XS

#3298 fix: lets move the developer guide more centrally
  content/en/v3/develop/developing/_index.md
  layouts/shortcodes/developcards.html
Labels: approved, size/S

#3299 fix: better home page
  content/en/_index.html
  content/en/v3/develop/developing/_index.md
Labels: approved, size/M

#3300 fix: add FAQ on adding users
  content/en/v3/develop/faq/config/general.md
Labels: approved, size/M

#3301 docs: April LTS release
  content/en/blog/news/2021-jx3-apr-lts.md
Labels: approved, size/S

#3302 fix: add first spike of on premise vault docs
  content/en/v3/admin/platforms/on-premise/_index.md
  content/en/v3/admin/platforms/on-premise/vault.md
  content/en/v3/admin/platforms/on-premise/webhooks.md
Labels: size/L

#3303 chore: add docs on enabling OAuth
  content/en/v3/admin/setup/ingress/oauth/_index.md
  content/en/v3/admin/setup/ingress/tls_dns/_index.md
  static/images/v3/gui-link1.png
  static/images/v3/oauth_gh.png
  static/images/v3/oauth_google.png
Labels: approved, size/L

#3304 chore: screenshot jx secret edit
  content/en/v3/admin/setup/ingress/oauth/_index.md
  static/images/v3/oauth_secret_edit.png
Labels: approved, size/XS

#3306 fix: 3.x GA announcement blog post
  content/en/_index.html
  content/en/blog/news/2021-jx-v3-ga.md
  content/en/v3/about/changes.md
Labels: approved, size/L

#3311 chore: fix link
  content/en/blog/news/2021-jx-v3-ga.md
Labels: approved, size/XS

#3312 fix: add scheduler link
  content/en/v3/develop/reference/files.md
Labels: size/XS

#3314 fix: edit this page links
  layouts/partials/page-meta-links.html
Labels: approved, size/XS

#3315 fix: add FAQ on post install hooks
  content/en/v3/develop/faq/general.md
Labels: size/S

#3316 fix: add FAQ
  content/en/v3/develop/faq/using.md
Labels: approved, size/S

#3317 fix: add docs for PR environment variables
  content/en/v3/develop/reference/variables.md
Labels: approved, size/M

#3318 fix: add docs on recreating pipelines
  content/en/v3/develop/pipelines/upgrading.md
Labels: size/S

#3319 fix: add docs on changing the bot user/token
  content/en/v3/develop/faq/config/secrets.md
  content/en/v3/develop/reference/variables.md
Labels: approved, size/M

#3320 fix: use better vault page
  content/en/v3/admin/setup/secrets/vault.md
  content/en/v3/develop/reference/files.md
Labels: approved, size/M

#3321 fix: observability chart
  content/en/v3/admin/guides/observability/platform-observability.md
Labels: approved, size/S
