Repository jenkins-x/jx-docs, pull requests merged in 2021-05, with the labels that each got.

#3323 fix: better office hours button
  content/en/community/_index.md
  content/en/community/office_hours/_index.md
Labels: approved, size/S

#3324 docs: add FAQ on webhooks
  content/en/v3/develop/faq/config/ingress.md
Labels: approved, size/S

#3322 fix: Update jenkinsfile.md
  content/en/v3/develop/create-project/jenkinsfile.md
Labels: approved, lgtm, ok-to-test, size/XS

#3325 fix: polish the multi cluster docs
  content/en/v3/admin/guides/multi-cluster/multi-cluster.md
Labels: approved, size/M

#3326 fix: make it clear to use https cloning
  content/en/v3/admin/platforms/azure/_index.md
  content/en/v3/admin/platforms/eks/_index.md
  content/en/v3/admin/platforms/google/_index.md
  content/en/v3/admin/platforms/minikube/_index.md
  content/en/v3/admin/platforms/on-premise/_index.md
  content/en/v3/admin/platforms/openshift/_index.md
  content/en/v3/admin/platforms/openshift/openshift-crc.md
Labels: approved, size/S

#3327 fix: add the v3 binary to the pre-req
  content/en/v3/admin/platforms/on-premise/_index.md
Labels: approved, size/XS

#3328 fix: update links to why-does-jenkins-x-use-helmfile-template
  content/en/v3/admin/guides/multi-cluster/multi-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#3332 docs: May 2021 LTS release notes
  content/en/blog/news/2021-jx3-lts-2021-05.md
Labels: approved, size/S

#3336 fix: add a blog on migrating from docker -> k8s
  content/en/blog/news/2021-no-docker.md
Labels: approved, size/L

#3337 fix: add link to kubedock
  content/en/blog/news/2021-no-docker.md
Labels: approved, size/XS

#3334 chore: add gitpod config for users easy to do contribution
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
Labels: size/S

#3341 docs: migrate more FAQ entries from v2
  content/en/v3/develop/faq/chatops.md
  content/en/v3/develop/faq/config/charts.md
  content/en/v3/develop/faq/config/ingress.md
  content/en/v3/develop/faq/issues.md
  content/en/v3/develop/faq/pipeline.md
  content/en/v3/develop/faq/previews.md
Labels: approved, size/L

#3344 chore: add some extra information about kind and filter values for new users
  content/en/v3/develop/ui/slack.md
Labels: approved, size/S

#3342 fix: typo
  content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md
Labels: needs-ok-to-test, size/XS

#3340 fix: remove old zoom link for office hours
  content/en/community/_index.md
  content/en/community/office_hours/_index.md
  content/es/community/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#3345 fix: typo
  content/en/v3/about/how-it-works.md
Labels: approved, size/XS

#3346 fix: regen the schema
  scripts/ci/update-website.sh
Labels: approved, size/XS

#3348 fix: add better FAQ on env config
  content/en/v3/develop/faq/config/charts.md
Labels: size/M
