Repository jenkins-x/jx-docs, pull requests merged in 2022-03, with the labels that each got.

#3556 fix: remove link to deleted tweet and add user and id to tweet shortcode
  .lighthouse/jenkins-x/pullrequest.yaml
  content/en/_index.html
  content/en/blog/news/2021-jx3-builtin-observability.md
Labels: approved, size/XS

#3546 fix: upgrade algolia docsearch to v3
  content/en/community/documentation/reference.md
  layouts/partials/head-css.html
  layouts/partials/navbar.html
  layouts/partials/scripts.html
  package-lock.json
  package.json
  static/css/style.css
Labels: approved, size/XXL, ok-to-test

#3555 fix: removed non-working links from docs
  content/en/v3/admin/platforms/on-premises/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3563 feat: add a gsoc 2022 follow up blog
  content/en/blog/news/2022-gsoc-followup.md
  content/en/blog/news/2022-gsoc.md
Labels: approved, size/M

#3564 refactor: make it more clear that v2 is not maintained
  config.toml
  content/en/blog/news/2022-gsoc-followup.md
  content/en/v3/admin/platforms/k3s/_index.md
  layouts/partials/breadcrumb.html
Labels: approved, size/M

#3568 docs: Edit the v3 / admin / platforms / k3s documentation
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/M, lgtm, ok-to-test

#3570 fix: Update OWNERS
  OWNERS
Labels: approved, size/M

#3571 docs: wrapping commands in a bash block
  content/en/v3/admin/platforms/eks/_index.md
Labels: approved, size/S, ok-to-test

#3573 fix: add gsod blog
  content/en/blog/news/2022-gsod.md
Labels: approved, size/L

#3574 fix: add gsod proposal and budget
  content/en/blog/news/2022-gsod.md
Labels: approved, size/L

#3578 feat: add new zoom link from cdf jx account
  content/en/community/_index.md
Labels: approved, size/XS, lgtm

#3577 fix: filter search results on language of current section
  layouts/partials/scripts.html
Labels: approved, size/XS, lgtm

#3580 docs: update readme and add CN-README
  Makefile
  README.md
  README_CN.md
Labels: approved, size/L, lgtm, ok-to-test
