Repository jenkins-x/jx-docs, pull requests merged in 2022-07, with the labels that each got.

#3623 fix: make it clear which ngrok forwarding url to use for hook service
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/S

#3624 fix: set XDG_CONFIG_HOME to `$HOME` to use credentials in git/credentials
  content/en/v3/develop/faq/using.md
Labels: approved, size/M

#3619 feat: add docs around jx concepts
  content/en/v3/about/concepts/_index.md
  content/en/v3/about/concepts/deployment-lifecycle.md
  content/en/v3/about/concepts/environments.md
  content/en/v3/about/concepts/pipeline-activity.md
  content/en/v3/about/concepts/source-repository.md
Labels: approved, size/XL

#3581 feat: add a maintainer guide for jenkins x
  content/en/community/maintainer_guide/_index.md
  content/en/community/maintainer_guide/go-upgrades.md
  content/en/community/maintainer_guide/infrastructure.md
  content/en/community/maintainer_guide/mentorship/_index.md
  content/en/community/maintainer_guide/mentorship/gsoc.md
Labels: approved, size/L

#3629 fix: security incidence report
  content/en/community/security.md
Labels: approved, size/XS, lgtm

#3633 docs: added k8s upgrade guide
  content/en/v3/admin/guides/k8s-upgrades/_index.md
Labels: size/S

#3635 fix: add information around catalog and version to go upgrade guide
  content/en/community/maintainer_guide/go-upgrades.md
Labels: approved, size/S

#3636 fix: move to svg instead of png
  content/en/_index.html
  static/images/logo/mqube-logo.png
  static/images/logo/mqube-logo.svg
Labels: approved, size/XS
