Repository jenkins-x/jx-docs, pull requests merged in 2022-09, with the labels that each got.

#3640 chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.18
  config.toml
Labels: size/XS, updatebot

#3642 docs: update go version in prerequisites section
  content/en/community/code/_index.md
Labels: approved, size/XS, ok-to-test

#3644 fix: Make regeneration of plugin docs work again
  .github/workflows/regenerate.yml
Labels: approved, size/S

#3645 fix: Make regeneration of plugin docs work again
  .github/workflows/regenerate.yml
Labels: approved, size/S

#3646 fix: Make regeneration of plugin docs work again
  .github/actions/create-pr-for-plugin-docs.yaml
  .github/workflows/regenerate.yml
Labels: approved, size/M

#3647 fix: Make regeneration of plugin docs work again
  .github/actions/create-pr-for-plugin-docs/action.yaml
Labels: approved, size/XS

#3648 fix: Make regeneration of plugin docs work again
  .github/actions/create-pr-for-plugin-docs/action.yaml
  .github/workflows/regenerate.yml
Labels: size/XS

#3649 fix: Make regeneration of plugin docs work again
  .github/actions/create-pr-for-plugin-docs/action.yaml
Labels: approved, size/XS

#3650 fix: Make regeneration of plugin docs work again
  regen-plugins.sh
Labels: approved, size/XS

#3643 docs: add support for supply chain security
  content/en/community/maintainer_guide/supply-chain-security.md
Labels: approved, size/L, ok-to-test

#3655 fix: changing docker-compose to docker compose in makefile
  Makefile
  content/en/community/documentation/_index.md
Labels: approved, size/S
