Repository jenkins-x/jx-docs, pull requests merged in 2022-01, with the labels that each got.

#3504 feat: added spot instances for building documentation
  content/en/v3/admin/guides/spot-instances/_index.md
Labels: approved, size/L, ok-to-test

#3505 refactor: add new links for office hours
  content/en/community/_index.md
  content/en/community/calendar.md
  content/en/community/office_hours/_index.md
  layouts/shortcodes/calendar.html
Labels: approved, size/M

#3503 fix: update _index.md
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3506 fix: change office hours to 1500 UTC
  content/en/community/_index.md
Labels: approved, size/XS

#3507 docs: added note on github maven permissions
  content/en/v3/admin/setup/config/repository.md
Labels: approved, size/XS, lgtm, ok-to-test

#3508 docs: Config GKE service account and AKS service principal
  content/en/v3/admin/platforms/azure/svc_principal.md
  content/en/v3/admin/platforms/google/svc_acct.md
  static/images/v3/cloud_app_admin.svg
  static/images/v3/roles_and_admin.svg
Labels: approved, lgtm, size/XXL, ok-to-test

#3511 fix: Display calendar in UTC
  layouts/shortcodes/calendar.html
Labels: approved, size/XS, lgtm, ok-to-test

#3513 docs: Updated k3s install command/ Vault Troubleshooting steps
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3514 New blog post about the Jenkins X survey
  content/en/blog/news/2022-survey.md
  layouts/partials/breadcrumb.html
Labels: approved, lgtm, size/S, ok-to-test

#3515 feat: add link to linux foundation course on jx
  content/en/v3/develop/_index.md
  content/en/v3/learning-resources/_index.md
Labels: approved, size/S

#3517 refactor: upgrade hugo docker image to 0.91.2
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  docker-compose.yml
Labels: approved, size/L

#3518 refactor: move pipelines to new format
  .gitignore
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S

#3520 docs: going through the install procedure - AWS Vault
  content/en/v3/admin/platforms/eks/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3524 chore: remove survey banner
  layouts/partials/breadcrumb.html
Labels: approved, size/XS

#3523 feat: add a section showing jx users
  content/en/_index.html
  static/images/logo/dexai-logo.jpg
  static/images/logo/mqube-logo.png
  static/images/logo/smart-ix-logo-colored.svg
Labels: approved, size/L

#3526 refactor: add id to jx users section
  content/en/_index.html
Labels: approved, size/XS

#3527 fix: add users id to the right section
  content/en/_index.html
Labels: approved, size/XS
