Repository jenkins-x/jx-docs, pull requests merged in 2022-06, with the labels that each got.

#3613 fix: minor typo in local chart installation instructions
  content/en/v3/develop/faq/config/charts.md
Labels: approved, size/M

#3612 fix: hide maturity and changes pages, obsolete
  content/en/v3/about/changes.md
  content/en/v3/about/maturity-matrix.md
Labels: approved, size/M

#3606 feat: add instructions to install vault operator and vault instance chart in k3s
  content/en/v3/admin/platforms/k3s/_index.md
Labels: size/L

#3607 Upgrade Jenkins Server Example page
  content/en/v3/admin/guides/jenkins/example.md
Labels: approved, size/L, lgtm, ok-to-test

#3616 fix: typo
  content/en/v3/develop/pipelines/_index.md
Labels: approved, size/XS

#3620 fix: add information around git credential store
  content/en/v3/develop/faq/using.md
Labels: approved, lgtm, size/S, ok-to-test

#3621 fix: add docs around multiple named ngrok tunnels
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/M

#3622 fix: upgrade docsy and hugo
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  config.toml
  docker-compose.yml
  go.mod
  go.sum
  layouts/partials/breadcrumb.html
Labels: approved, size/M
