Repository jenkins-x/jx-docs, pull requests merged in 2022-11, with the labels that each got.

#3666 fix: add jx-community repo link
  content/en/community/_index.md
Labels: approved, size/XS

#3668 ci: fix jx preview prs
  .lighthouse/jenkins-x/preview.yaml
  charts/preview/templates/ingress.yaml
Labels: approved, size/S

#3665 fix: Remove deprecated modes of communication
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  content/en/community/_index.md
  layouts/shortcodes/calendar.html
  layouts/shortcodes/contributors.html
  layouts/shortcodes/contributors.json
Labels: approved, size/XXL

#3672 Remove mailchimp
  README.md
  content/en/_index.html
  content/en/community/newsletter/_index.md
  layouts/partials/scripts.html
  layouts/shortcodes/mailchimp.html
Labels: approved, size/M

#3669 docs: GSoC report
  content/en/blog/news/2022-GSoC-2022-Supply-Chain-Security-Final-Report.md
Labels: approved, size/M

#3676 fixbuild
  config.toml
Labels: size/XS

#3679 fix: add version tag to k3s install command
  content/en/v3/admin/platforms/k3s/_index.md
Labels: approved, size/XS

#3677 fix: add info on the procedure when restarting minikube session
  content/en/v3/admin/platforms/minikube/_index.md
Labels: approved, size/XS

#3673 docs: add gsoc 2022 work report
  content/en/blog/news/2022-gsoc-work-report.md
  static/images/gsoc-work-report-22/homepage.png
  static/images/gsoc-work-report-22/pipelineDetailsPage.png
  static/images/gsoc-work-report-22/pipelineDetailsPageStopBtn.png
  static/images/gsoc-work-report-22/pipelinesPage.png
  static/images/gsoc-work-report-22/pipelinesPageStopBtn.png
Labels: approved, size/L

#3681 fix: update gsoc report
  content/en/blog/news/2022-GSoC-2022-Supply-Chain-Security-Final-Report.md
Labels: approved, size/M

#3667 fix: modify k3s docs
  content/en/v3/admin/platforms/k3s/_index.md
  content/en/v3/develop/faq/ngrok.md
Labels: approved, size/L
