Repository jenkins-x/jx-docs, pull requests merged in 2022-08, with the labels that each got.

#3632 docs: write a blog post about SBOM
  content/en/blog/news/2022-introduction-to-sbom.md
  content/en/blog/news/2022-sbom-formats-comparison.md
  content/en/blog/news/2022-sbom-generation-tools.md
  static/images/sbom-guide/cyclonedx-high-level-object-model-small.svg
  static/images/sbom-guide/microsoft-sbom.png
  static/images/sbom-guide/spdx-2.2-document.png
  static/images/sbom-guide/supply-chain.png
  static/images/sbom-guide/swid-tags-lifecycle.png
Labels: approved, size/XL, lgtm, ok-to-test

#3626 fix: new tagline
  content/en/_index.html
Labels: approved, size/XS

#3638 fix: remove /docs
  layouts/_default/sitemap.xml
  layouts/partials/head.html
  layouts/partials/page-description.html
  layouts/robots.txt
Labels: approved, size/M
