Repository jenkins-x/jx-docs, pull requests merged in 2022-04, with the labels that each got.

#3587 fix: remove v tag from docsy package name
  go.mod
  go.sum
Labels: approved, lgtm, size/S, ok-to-test

#3589 fix: Minikube set kubernetes version
  content/en/v3/admin/platforms/minikube/_index.md
Labels: approved, size/XS, lgtm

#3590 feat: project proposal template for GSOC
  content/en/blog/news/2022-gsoc-followup.md
  content/en/blog/news/2022-gsoc-project-template.md
  content/en/blog/news/2022-gsoc.md
Labels: approved, size/M

#3591 fix: minor cleanup of project template
  content/en/blog/news/2022-gsoc-followup.md
  content/en/blog/news/2022-gsoc-project-template.md
Labels: approved, size/S

#3592 fix: jx cli install - remove the top line about "beta jx" version
  content/en/v3/admin/setup/jx3/_index.md
Labels: approved, size/XS, lgtm

#3593 chore: update Hugo to 0.95.0
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  docker-compose.yml
Labels: approved, lgtm, size/S, ok-to-test

#3595 fix: fix typo
  content/en/v3/about/what.md
Labels: approved, size/XS, ok-to-test

#3584 docs: updating contribution guide
  content/en/community/code/_index.md
Labels: approved, size/S, ok-to-test

#3600 docs: k8s 1.22 and tekton breaking change
  content/en/blog/news/2022-04-22-k8s-122-tekton.md
Labels: approved, size/M

#3602 fix: remove resource request from step template
  .lighthouse/jenkins-x/preview.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S
