Repository jenkins-x/jx-docs, pull requests merged in 2022-02, with the labels that each got.

#3525 Fix: top-padding in tag-line
  content/en/_index.html
  layouts/partials/navbar.html
  package-lock.json
Labels: approved, lgtm, size/XXL, ok-to-test

#3530 Fixed git config http.sslVerify typo
  content/en/v3/admin/setup/operator/_index.md
  content/en/v3/develop/reference/jx/admin/operator/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3509 feat: January updates from Jenkins X
  content/en/blog/news/jx-202201.md
Labels: approved, size/M

#3531 docs: extended survey period
  content/en/blog/news/2022-survey.md
  layouts/partials/breadcrumb.html
Labels: approved, size/XS, lgtm, ok-to-test

#3533 Adding Ticket logo
  content/en/_index.html
  static/images/logo/ticket-logo.svg
Labels: approved, size/L, lgtm, ok-to-test

#3536 fix: alignment of text & adding new links
  config.toml
  layouts/partials/footer.html
Labels: approved, size/M, lgtm, ok-to-test

#3537 fix: new icons in /community route
  config.toml
Labels: approved, size/XS, lgtm, ok-to-test

#3538 docs: removed builder-images and contribute-dns from code section
  content/en/community/code/builder-images.md
  content/en/community/code/contribute_dns.md
Labels: approved, size/L, lgtm, ok-to-test

#3542 docs: removed survey header
  layouts/partials/breadcrumb.html
Labels: approved, size/XS, lgtm, ok-to-test

#3543 fix: added mentor medier logo + alt texts
  content/en/_index.html
  static/images/logo/mentormedier-logo.svg
Labels: approved, size/M, lgtm, ok-to-test

#3541 fix: broken links in docs
  content/en/v3/develop/apps/_index.md
  content/en/v3/develop/create-project/_index.md
  content/en/v3/develop/pipelines/_index.md
Labels: approved, size/XS, lgtm, ok-to-test

#3545 docs: tailosoft logo
  content/en/_index.html
  static/images/logo/tailosoft-logo.svg
Labels: approved, lgtm, size/S, ok-to-test

#3539 docs: survey results
  content/en/blog/news/2022-02-15-survey-results-details.md
  content/en/blog/news/2022-02-15-survey-results.md
  static/images/survey-2022-1/area-of-work.png
  static/images/survey-2022-1/cloud-provider.png
  static/images/survey-2022-1/enjoy-most.png
  static/images/survey-2022-1/hard-to-find-information.png
  static/images/survey-2022-1/improving.png
  static/images/survey-2022-1/jx-versions.png
  static/images/survey-2022-1/office-hours.png
  static/images/survey-2022-1/other-feedback.png
  static/images/survey-2022-1/parts-rating.png
  static/images/survey-2022-1/people-in-company.png
  static/images/survey-2022-1/where-information.png
Labels: approved, size/L, ok-to-test

#3544 fix: proper mentor-medier logo
  content/en/_index.html
  static/images/logo/mentormedier-logo.svg
Labels: approved, size/L, lgtm, ok-to-test

#3547 feat: add a blog with project ideas for gsoc 2022
  content/en/blog/news/2022-gsoc.md
Labels: approved, size/L

#3550 fix: add the link to quickstart documentation and troubleshooting
  content/en/v3/develop/create-project/_index.md
Labels: approved, size/XS

#3553 chore: add difficulty rating to gsoc project ideas
  content/en/blog/news/2022-gsoc.md
Labels: approved, size/M

#3554 fix: mention running port forward when editing secret in vault
  content/en/v3/develop/faq/config/secrets.md
Labels: approved, size/L
