Repository jenkins-x/jx-docs, pull requests merged in 2025-01, with the labels that each got.

#3752 docs: remove references to twitter
  config.toml
  content/en/_index.html
Labels: approved, size/S

#3748 fix: remove broken reference to discourse page
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XS, needs-ok-to-test

#3751 add instruction regarding connect to eks
  content/en/v3/admin/platforms/eks/_index.md
Labels: approved, size/XS

#3754 docs: roadmap
  content/en/community/roadmap.md
Labels: approved, size/S
